diff --git a/portable/GCC/ARM_CM3/Makefile b/portable/GCC/ARM_CM3/Makefile
new file mode 100644
index 000000000..7df33506f
--- /dev/null
+++ b/portable/GCC/ARM_CM3/Makefile
@@ -0,0 +1 @@
+obj-y += port.o
\ No newline at end of file
