-include $(KCONFIG_CONFIG)
obj-y += clib/source/
obj-y += aspeed/
obj-y += freertos_plus/freertos_plus_cli/
obj-y += getopt/
obj-$(CONFIG_LIBRARIES_LOG) += log/src/
obj-$(CONFIG_LIBRARIES_CMBACKTRACE) += CmBacktrace/cm_backtrace/
