diff --git a/Makefile b/Makefile
new file mode 100644
index 000000000..69d9fbe7f
--- /dev/null
+++ b/Makefile
@@ -0,0 +1,5 @@
+-include $(KCONFIG_CONFIG)
+obj-y += event_groups.o list.o queue.o stream_buffer.o tasks.o timers.o
+obj-$(CONFIG_USE_CO_ROUTINES) += croutine.o
+obj-y += portable/GCC/$(OS_PORT)/
+obj-y += portable/MemMang/
\ No newline at end of file
