/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "plat_sensor_table.h"
#include <stdio.h>
#include <string.h>
#include "plat_i2c.h"
#include "ast_adc.h"
#include "plat_hook.h"
#include "plat_class.h"
#include "plat_modbus.h"
#include "plat_util.h"
#include "modbus_server.h"
#include "plat_isr.h"
#include "plat_threshold.h"
#include <logging/log.h>
#include "plat_class.h"
#include <tmp421.h>

LOG_MODULE_REGISTER(plat_sensor_table);

#define I2C_MAX_RETRY 3
#define SIZEOF_NCT7363_INIT_ARGS 18

struct k_thread quick_sensor_poll;
K_KERNEL_STACK_MEMBER(quick_sensor_poll_stack, 1024);
k_tid_t quick_sensor_tid;

uint8_t quick_sensor[] = { SENSOR_NUM_BPB_CDU_COOLANT_LEAKAGE_VOLT_V,
			   SENSOR_NUM_BPB_RACK_COOLANT_LEAKAGE_VOLT_V };

/* quick sensor */
void quick_sensor_poll_handler(void *arug0, void *arug1, void *arug2)
{
	k_msleep(1000); // delay 1 second to wait for drivers ready before start sensor polling
	int quick_sensor_poll_interval_ms = 30;

	while (1) {
		if (!get_sensor_init_done_flag()) {
			k_msleep(quick_sensor_poll_interval_ms);
			continue;
		}

		if (!get_sensor_poll_enable_flag()) {
			k_msleep(quick_sensor_poll_interval_ms);
			continue;
		}

		for (uint8_t i = 0; i < ARRAY_SIZE(quick_sensor); i++) {
			int reading = 0;
			uint8_t status;

			status = get_sensor_reading(sensor_config, sensor_config_count,
						    quick_sensor[i], &reading, GET_FROM_SENSOR);
		}

		k_msleep(quick_sensor_poll_interval_ms);
	}
}

void quick_sensor_poll_init()
{
	quick_sensor_tid = k_thread_create(&quick_sensor_poll, quick_sensor_poll_stack,
					   K_THREAD_STACK_SIZEOF(quick_sensor_poll_stack),
					   quick_sensor_poll_handler, NULL, NULL, NULL,
					   CONFIG_MAIN_THREAD_PRIORITY, 0, K_NO_WAIT);
	k_thread_name_set(&quick_sensor_poll, "quick_sensor_poll");
	return;
}

bool post_quick_sensor_read(sensor_cfg *cfg, void *args, int *reading)
{
	CHECK_NULL_ARG_WITH_RETURN(cfg, false);
	bool ret = post_ads112c_read(cfg, args, reading);

	if (ret) {
		float val = 0;
		const sensor_val *sval = (sensor_val *)reading;
		val = (sval->integer * 1000 + sval->fraction) / 1000.0;

		if ((val > 0) && (val < 3.1))
			aalc_leak_behavior(cfg->num);
	}

	return ret;
}

sensor_cfg plat_sensor_config[] = {
	/* number,                  type,       port,      address,      offset,
	   access check, arg0, arg1, sample_count, cache, cache_status, mux_address, mux_offset,
	   pre_sensor_read_fn, pre_sensor_read_args, post_sensor_read_fn, post_sensor_read_args  */
	{ SENSOR_NUM_FB_1_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[0] },
	{ SENSOR_NUM_FB_2_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[1] },
	{ SENSOR_NUM_FB_3_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[2] },
	{ SENSOR_NUM_FB_4_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[3] },
	{ SENSOR_NUM_FB_5_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[4] },
	{ SENSOR_NUM_FB_6_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[5] },
	{ SENSOR_NUM_FB_7_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &nct7363_init_args[6] },
	{ SENSOR_NUM_FB_8_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, NULL, &nct7363_init_args[7] },
	{ SENSOR_NUM_FB_9_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS7, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[8] },
	{ SENSOR_NUM_FB_10_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[9] },
	{ SENSOR_NUM_FB_11_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS7, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[10] },
	{ SENSOR_NUM_FB_12_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[11] },
	{ SENSOR_NUM_FB_13_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS7, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[12] },
	{ SENSOR_NUM_FB_14_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[13] },
	{ SENSOR_NUM_PB_1_PUMP_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[14] },
	{ SENSOR_NUM_PB_1_FAN_1_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[14] },
	{ SENSOR_NUM_PB_1_FAN_2_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_7_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[14] },
	{ SENSOR_NUM_PB_2_PUMP_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[15] },
	{ SENSOR_NUM_PB_2_FAN_1_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[15] },
	{ SENSOR_NUM_PB_2_FAN_2_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_7_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[15] },
	{ SENSOR_NUM_PB_3_PUMP_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[16] },
	{ SENSOR_NUM_PB_3_FAN_1_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[16] },
	{ SENSOR_NUM_PB_3_FAN_2_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_7_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[16] },
	{ SENSOR_NUM_MB_FAN1_TACH_RPM, sensor_dev_ast_tach, TACH_PORT0, NONE, AST_TACH_RPM,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &ast_tach_init_args[0] },
	{ SENSOR_NUM_MB_FAN2_TACH_RPM, sensor_dev_ast_tach, TACH_PORT1, NONE, AST_TACH_RPM,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &ast_tach_init_args[1] },
	{ SENSOR_NUM_BPB_RACK_LEVEL_1, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR,
	  NCT7363_GPIO_READ_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &nct7363_init_args[17] },
	{ SENSOR_NUM_BPB_RACK_LEVEL_2, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR,
	  NCT7363_GPIO_READ_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &nct7363_init_args[17] },
	{ SENSOR_NUM_BPB_RPU_LEVEL, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR,
	  NCT7363_GPIO_READ_OFFSET, stby_access, NCT7363_7_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &nct7363_init_args[17] },
	{ SENSOR_NUM_SB_HEX_PRESSURE_1_P_KPA, sensor_dev_ads112c, I2C_BUS9, SB_ADS112C_1_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_ads112c_read, &ads112c_post_args[1],
	  &ads112c_init_args[1] },
	{ SENSOR_NUM_SB_HEX_PRESSURE_2_P_KPA, sensor_dev_ads112c, I2C_BUS9, SB_ADS112C_1_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_ads112c_read, &ads112c_post_args[1],
	  &ads112c_init_args[2] },
	{ SENSOR_NUM_BPB_RACK_PRESSURE_3_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, &ads112c_post_args[1], &ads112c_init_args[3] },
	{ SENSOR_NUM_BPB_RACK_PRESSURE_4_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, &ads112c_post_args[1], &ads112c_init_args[4] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_INLET_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, &ads112c_post_args[1], &ads112c_init_args[2] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_OUTLET_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, &ads112c_post_args[1], &ads112c_init_args[1] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_FLOW_RATE_LPM, sensor_dev_ads112c, I2C_BUS5,
	  BPB_ADS112C_4_ADDR, ADS112C_READ_OUTPUT_RAW, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, &ads112c_post_args[0], &ads112c_init_args[5] },
	{ SENSOR_NUM_FB_1_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[0] },
	{ SENSOR_NUM_FB_2_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[1] },
	{ SENSOR_NUM_FB_3_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[2] },
	{ SENSOR_NUM_FB_4_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[3] },
	{ SENSOR_NUM_FB_5_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[4] },
	{ SENSOR_NUM_FB_6_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[5] },
	{ SENSOR_NUM_FB_7_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &hdc1080_init_args[6] },
	{ SENSOR_NUM_FB_8_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, NULL, &hdc1080_init_args[7] },
	{ SENSOR_NUM_FB_9_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[8] },
	{ SENSOR_NUM_FB_10_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[9] },
	{ SENSOR_NUM_FB_11_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[10] },
	{ SENSOR_NUM_FB_12_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[11] },
	{ SENSOR_NUM_FB_13_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[12] },
	{ SENSOR_NUM_FB_14_HEX_OUTLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[13] },
	{ SENSOR_NUM_PB_1_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[14] },
	{ SENSOR_NUM_PB_2_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[15] },
	{ SENSOR_NUM_PB_3_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[16] },
	{ SENSOR_NUM_BB_TMP75_TEMP_C, sensor_dev_tmp75, I2C_BUS4, BB_TMP75_ADDR, TMP75_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_BPB_RPU_OUTLET_TEMP_C, sensor_dev_tmp75, I2C_BUS4, BPB_TMP75_ADDR,
	  TMP75_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_BPB_RPU_COOLANT_INLET_TEMP_C, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_2_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read,
	  &ads112c_post_args[2], &ads112c_init_args[6] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_OUTLET_TEMP_C, sensor_dev_ads112c, I2C_BUS3,
	  BPB_ADS112C_1_ADDR, ADS112C_READ_OUTPUT_RAW, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, &ads112c_post_args[2], &ads112c_init_args[6] },
	{ SENSOR_NUM_BPB_HEX_WATER_INLET_TEMP_C, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_3_ADDR,
	  ADS112C_READ_OUTPUT_RAW, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read,
	  &ads112c_post_args[5], &ads112c_init_args[6] },
	{ SENSOR_NUM_MB_RPU_AIR_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS10, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &hdc1080_init_args[17] },
	{ SENSOR_NUM_PDB_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS9, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[18] },
	{ SENSOR_NUM_FB_1_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[0] },
	{ SENSOR_NUM_FB_2_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[1] },
	{ SENSOR_NUM_FB_3_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[2] },
	{ SENSOR_NUM_FB_4_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[3] },
	{ SENSOR_NUM_FB_5_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[4] },
	{ SENSOR_NUM_FB_6_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[5] },
	{ SENSOR_NUM_FB_7_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &hdc1080_init_args[6] },
	{ SENSOR_NUM_FB_8_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, NULL, &hdc1080_init_args[7] },
	{ SENSOR_NUM_FB_9_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[8] },
	{ SENSOR_NUM_FB_10_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[9] },
	{ SENSOR_NUM_FB_11_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[10] },
	{ SENSOR_NUM_FB_12_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[11] },
	{ SENSOR_NUM_FB_13_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[12] },
	{ SENSOR_NUM_FB_14_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[13] },
	{ SENSOR_NUM_MB_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS10, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  evt_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &hdc1080_init_args[17] },
	{ SENSOR_NUM_PDB_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS9, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, pre_PCA9546A_read, &bus_9_PCA9546A_configs[1], post_PCA9546A_read,
	  NULL, &hdc1080_init_args[18] },
	{ SENSOR_NUM_PB_1_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[14] },
	{ SENSOR_NUM_PB_2_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[15] },
	{ SENSOR_NUM_PB_3_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[16] },
	{ SENSOR_NUM_BPB_CDU_COOLANT_LEAKAGE_VOLT_V, sensor_dev_ads112c, I2C_BUS5,
	  BPB_ADS112C_1_ADDR, ADS112C_READ_OUTPUT_RAW, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_quick_sensor_read, &ads112c_post_args[3], &ads112c_init_args[8] },
	{ SENSOR_NUM_BPB_RACK_COOLANT_LEAKAGE_VOLT_V, sensor_dev_ads112c, I2C_BUS5,
	  BPB_ADS112C_3_ADDR, ADS112C_READ_OUTPUT_RAW, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_quick_sensor_read, &ads112c_post_args[3], &ads112c_init_args[8] },
	{ SENSOR_NUM_SB_TTV_COOLANT_LEAKAGE_1_VOLT_V, sensor_dev_ads112c, I2C_BUS9,
	  SB_ADS112C_3_ADDR, ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  pre_PCA9546A_read, &bus_9_PCA9546A_configs[0], post_ads112c_read, &ads112c_post_args[4],
	  &ads112c_init_args[0] },
	{ SENSOR_NUM_SB_TTV_COOLANT_LEAKAGE_2_VOLT_V, sensor_dev_ads112c, I2C_BUS9,
	  SB_ADS112C_2_ADDR, ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  pre_PCA9546A_read, &bus_9_PCA9546A_configs[0], post_ads112c_read, &ads112c_post_args[4],
	  &ads112c_init_args[0] },
	{ SENSOR_NUM_SB_TTV_COOLANT_LEAKAGE_3_VOLT_V, sensor_dev_ads112c, I2C_BUS9,
	  SB_ADS112C_2_ADDR, ADS112C_READ_OUTPUT_RAW, stby_access, ENABLE_RESET_CFG_REG, 0,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  pre_PCA9546A_read, &bus_9_PCA9546A_configs[0], post_ads112c_read, &ads112c_post_args[4],
	  &ads112c_init_args[7] },
	// ADC
	{ SENSOR_NUM_V_12_AUX, sensor_dev_ast_adc, ADC_PORT0, NONE, NONE, stby_access, 676, 100,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_5_AUX, sensor_dev_ast_adc, ADC_PORT1, NONE, NONE, stby_access, 711, 200,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_3_3_AUX, sensor_dev_ast_adc, ADC_PORT2, NONE, NONE, stby_access, 2, 1,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_1_2_AUX, sensor_dev_ast_adc, ADC_PORT3, NONE, NONE, stby_access, 1, 1,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_5_USB, sensor_dev_ast_adc, ADC_PORT4, NONE, NONE, stby_access, 711, 200,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	// PDB sense differential voltages
	{ SENSOR_NUM_PDB_48V_SENSE_DIFF_POS_VOLT_V, sensor_dev_ina238, I2C_BUS9,
	  PDB_INA238_U14_ADDR, INA238_VSHUNT_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[1], post_PCA9546A_read, NULL, &ina238_init_args[0] },
	{ SENSOR_NUM_PDB_48V_SENSE_DIFF_NEG_VOLT_V, sensor_dev_ina238, I2C_BUS9,
	  PDB_INA238_U15_ADDR, INA238_VSHUNT_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[1], post_PCA9546A_read, NULL, &ina238_init_args[1] },

	//	Brick
	{ SENSOR_NUM_BPB_BRICK_12V_VIN_VOLT_V, sensor_dev_e50sn12051, I2C_BUS4, BPB_BRICK_12V_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &e50sn12051_init_args[0] },
	{ SENSOR_NUM_BPB_BRICK_12V_VOUT_VOLT_V, sensor_dev_e50sn12051, I2C_BUS4, BPB_BRICK_12V_ADDR,
	  PMBUS_READ_VOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &e50sn12051_init_args[0] },
	{ SENSOR_NUM_BPB_BRICK_12V_IOUT_CURR_A, sensor_dev_e50sn12051, I2C_BUS4, BPB_BRICK_12V_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &e50sn12051_init_args[0] },
	{ SENSOR_NUM_BPB_BRICK_12V_TEMP_C, sensor_dev_e50sn12051, I2C_BUS4, BPB_BRICK_12V_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &e50sn12051_init_args[0] },
};

sensor_cfg hsc_sensor_config_table[] = {
	{ SENSOR_NUM_FB_1_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_1_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_1_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_1_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_2_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_2_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_2_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_2_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_3_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_3_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_3_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_3_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_4_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_4_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_4_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_4_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_5_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_5_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_5_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_5_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_6_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_6_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_6_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_6_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_7_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_7_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_7_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_7_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_8_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_8_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_8_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_8_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_adm1272_read, NULL, &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_9_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_9_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_9_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_9_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_10_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_10_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_10_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_10_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_11_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_11_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_11_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_11_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_12_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_12_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_12_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_12_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_13_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_13_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_13_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_13_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_14_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[13] },
	{ SENSOR_NUM_FB_14_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[13] },
	{ SENSOR_NUM_FB_14_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[13] },
	{ SENSOR_NUM_FB_14_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[13] },
	{ SENSOR_NUM_PB_1_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_1_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_1_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_1_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_adm1272_read, NULL, &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_2_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_2_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_2_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_2_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_adm1272_read, NULL, &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_3_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[16] },
	{ SENSOR_NUM_PB_3_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[16] },
	{ SENSOR_NUM_PB_3_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[16] },
	{ SENSOR_NUM_PB_3_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_adm1272_read, NULL, &adm1272_init_args[16] },
	{ SENSOR_NUM_BB_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BB_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BB_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BB_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BPB_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[18] },
	{ SENSOR_NUM_BPB_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[18] },
	{ SENSOR_NUM_BPB_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[18] },
	{ SENSOR_NUM_BPB_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[18] },
};
sensor_cfg tmp421_config_table[] = {
	{ SENSOR_NUM_SB_HEX_AIR_INLET_1_TEMP_C, sensor_dev_tmp421, I2C_BUS9, SB_TMP421_1_ADDR,
	  TMP421_REMOTE_TEMPERATRUE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
	{ SENSOR_NUM_SB_HEX_AIR_INLET_2_TEMP_C, sensor_dev_tmp421, I2C_BUS9, SB_TMP421_2_ADDR,
	  TMP421_REMOTE_TEMPERATRUE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
	{ SENSOR_NUM_SB_HEX_AIR_INLET_3_TEMP_C, sensor_dev_tmp421, I2C_BUS9, SB_TMP421_3_ADDR,
	  TMP421_REMOTE_TEMPERATRUE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
	{ SENSOR_NUM_SB_HEX_AIR_INLET_4_TEMP_C, sensor_dev_tmp421, I2C_BUS9, SB_TMP421_4_ADDR,
	  TMP421_REMOTE_TEMPERATRUE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
};
sensor_cfg nct214_config_table[] = {
	{ SENSOR_NUM_SB_HEX_AIR_INLET_1_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_1_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[0] },
	{ SENSOR_NUM_SB_HEX_AIR_INLET_2_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_2_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[1] },
	{ SENSOR_NUM_SB_HEX_AIR_INLET_3_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_3_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[2] },
	{ SENSOR_NUM_SB_HEX_AIR_INLET_4_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_4_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[3] },
};

sensor_cfg plat_def_sensor_config[] = {
	{ SENSOR_NUM_RPU_PWR_W, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_RPU_PWR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HEX_PWR_W, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_HEX_PWR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_AALC_TOTAL_PWR_W, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_TOTAL_PWR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HEX_CURR_A, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_HEX_CURR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HEX_EXTERNAL_Y_FILTER, sensor_dev_plat_def_sensor, 0, 0,
	  PLAT_DEF_SENSOR_HEX_EXTERNAL_Y_FILTER, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  NULL },
	{ SENSOR_NUM_FAN_PRSNT, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_FAN_PRSNT,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_SB_HEX_AIR_INLET_AVG_TEMP_C, sensor_dev_plat_def_sensor, 0, 0,
	  PLAT_DEF_SENSOR_SB_HEX_AIR_INLET_AVG_TEMP, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  NULL },
	{ SENSOR_NUM_COOLING_CAPACITY, sensor_dev_plat_def_sensor, 0, 0,
	  PLAT_DEF_SENSOR_COOLING_CAPACITY, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  NULL },
};

const int SENSOR_CONFIG_SIZE = ARRAY_SIZE(plat_sensor_config) +
			       ARRAY_SIZE(hsc_sensor_config_table) +
			       ARRAY_SIZE(nct214_config_table) + ARRAY_SIZE(plat_def_sensor_config);

static uint8_t get_temp_sensor_mfr_id(uint8_t bus, uint8_t addr, uint8_t mfr_id_offset)
{
	I2C_MSG msg = { 0 };
	msg.bus = bus;
	msg.target_addr = addr;
	msg.rx_len = 1;
	msg.tx_len = 1;
	msg.data[0] = mfr_id_offset;
	if (i2c_master_read(&msg, I2C_MAX_RETRY)) {
		LOG_ERR("Failed to read TEMP 0x%x module MFR_ID", addr);
		return 0;
	}

	return msg.data[0];
}

uint32_t get_pmbus_mfr_id(uint8_t bus, uint8_t addr)
{
	I2C_MSG msg = { 0 };
	msg.bus = bus;
	msg.target_addr = addr;
	msg.rx_len = 4;
	msg.tx_len = 1;
	msg.data[0] = PMBUS_MFR_ID;
	if (i2c_master_read(&msg, I2C_MAX_RETRY)) {
		LOG_ERR("Failed to read HSC module MFR_ID");
		return 0;
	}

	return (msg.data[3] << 16) | (msg.data[2] << 8) | msg.data[1];
}

#define HSC_CONFIG_FB 0x00
#define HSC_CONFIG_BPB 0x01
#define HSC_CONFIG_BB 0x02
#define HSC_CONFIG_PB 0x03

static void hsc_config(uint8_t type)
{
	/* default sensor config is adm1272
	 * EVT stage: 1st and 2nd source have same i2c addr, identify by MFR_ID reg
	 * DVT stage: 1st and 2nd source have different i2c addr, identify by i2c addr
	 * Fan Board EVT: 0x22, 		DVT + XDP710: 0x2A
	 * Backplane Board EVT: 0x20, 	DVT + XDP710: 0x28
	 * Pump Board : 0x24, 			XDP710: 0x2C
	 * Bridge Board : 0x26, 		XDP710: 0x2E 
	 */

#define ADM1272_MFR_ID 0x494441
#define XDP710_MFR_ID 0x004649
#define XDP710_FB_ADDR_DVT (0x2A >> 1)
#define XDP710_BPB_ADDR_DVT (0x28 >> 1)
#define XDP710_PB_ADDR (0x2C >> 1)
#define XDP710_BB_ADDR (0x2E >> 1)

	uint8_t fb_sen_tbl[] = { SENSOR_NUM_FB_1_HSC_TEMP_C,
				 SENSOR_NUM_FB_1_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_1_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_1_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_2_HSC_TEMP_C,
				 SENSOR_NUM_FB_2_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_2_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_2_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_3_HSC_TEMP_C,
				 SENSOR_NUM_FB_3_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_3_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_3_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_4_HSC_TEMP_C,
				 SENSOR_NUM_FB_4_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_4_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_4_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_5_HSC_TEMP_C,
				 SENSOR_NUM_FB_5_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_5_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_5_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_6_HSC_TEMP_C,
				 SENSOR_NUM_FB_6_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_6_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_6_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_7_HSC_TEMP_C,
				 SENSOR_NUM_FB_7_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_7_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_7_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_8_HSC_TEMP_C,
				 SENSOR_NUM_FB_8_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_8_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_8_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_9_HSC_TEMP_C,
				 SENSOR_NUM_FB_9_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_9_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_9_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_10_HSC_TEMP_C,
				 SENSOR_NUM_FB_10_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_10_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_10_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_11_HSC_TEMP_C,
				 SENSOR_NUM_FB_11_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_11_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_11_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_12_HSC_TEMP_C,
				 SENSOR_NUM_FB_12_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_12_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_12_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_13_HSC_TEMP_C,
				 SENSOR_NUM_FB_13_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_13_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_13_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_14_HSC_TEMP_C,
				 SENSOR_NUM_FB_14_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_14_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_14_HSC_P48V_PIN_PWR_W };

	uint8_t bpb_sen_tbl[] = { SENSOR_NUM_BPB_HSC_P48V_TEMP_C,
				  SENSOR_NUM_BPB_HSC_P48V_VIN_VOLT_V,
				  SENSOR_NUM_BPB_HSC_P48V_IOUT_CURR_A,
				  SENSOR_NUM_BPB_HSC_P48V_PIN_PWR_W };

	uint8_t pb_sen_tbl[] = {
		SENSOR_NUM_PB_1_HSC_P48V_TEMP_C,      SENSOR_NUM_PB_1_HSC_P48V_VIN_VOLT_V,
		SENSOR_NUM_PB_1_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_PB_1_HSC_P48V_PIN_PWR_W,
		SENSOR_NUM_PB_2_HSC_P48V_TEMP_C,      SENSOR_NUM_PB_2_HSC_P48V_VIN_VOLT_V,
		SENSOR_NUM_PB_2_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_PB_2_HSC_P48V_PIN_PWR_W,
		SENSOR_NUM_PB_3_HSC_P48V_TEMP_C,      SENSOR_NUM_PB_3_HSC_P48V_VIN_VOLT_V,
		SENSOR_NUM_PB_3_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_PB_3_HSC_P48V_PIN_PWR_W
	};

	uint8_t bb_tbl[] = { SENSOR_NUM_BB_HSC_P48V_TEMP_C, SENSOR_NUM_BB_HSC_P48V_VIN_VOLT_V,
			     SENSOR_NUM_BB_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_BB_HSC_P48V_PIN_PWR_W };

	uint16_t sen_nums = 0;
	uint8_t *sen_tbl = NULL;
	uint8_t dvt_xdp_addr = 0;
	xdp710_init_arg *xdp_init_arr = NULL;
	switch (type) {
	case HSC_CONFIG_FB:
		sen_nums = ARRAY_SIZE(fb_sen_tbl);
		sen_tbl = fb_sen_tbl;
		dvt_xdp_addr = XDP710_FB_ADDR_DVT;
		xdp_init_arr = &xdp710_init_args[0];
		break;
	case HSC_CONFIG_BPB:
		sen_nums = ARRAY_SIZE(bpb_sen_tbl);
		sen_tbl = bpb_sen_tbl;
		dvt_xdp_addr = XDP710_BPB_ADDR_DVT;
		xdp_init_arr = &xdp710_init_args[3];
		break;
	case HSC_CONFIG_PB:
		sen_nums = ARRAY_SIZE(pb_sen_tbl);
		sen_tbl = pb_sen_tbl;
		dvt_xdp_addr = XDP710_PB_ADDR;
		xdp_init_arr = &xdp710_init_args[1];
		break;
	case HSC_CONFIG_BB:
		sen_nums = ARRAY_SIZE(bb_tbl);
		sen_tbl = bb_tbl;
		dvt_xdp_addr = XDP710_BB_ADDR;
		xdp_init_arr = &xdp710_init_args[2];
		break;
	default:
		LOG_ERR("Unknown HSC module type(%d)", type);
		return;
	}
	LOG_INF("sen_nums = %d", sen_nums);

	for (uint8_t i = 0; i < ARRAY_SIZE(hsc_sensor_config_table); i++) {
		sensor_cfg *p = hsc_sensor_config_table + i;

		for (uint8_t j = 0; j < sen_nums; j++) {
			if (p->num != *(sen_tbl + j))
				continue;
			if (!pre_PCA9546A_read(p, p->pre_sensor_read_args))
				LOG_ERR("pre lock mutex fail !");

			// use default address to identify the HSC module
			const uint32_t mfr_id = get_pmbus_mfr_id(p->port, p->target_addr);
			LOG_INF("Sensor %x's HSC module MFR_ID: 0x%06x", p->num, mfr_id);

			if (!post_PCA9546A_read(p, p->pre_sensor_read_args, 0))
				LOG_ERR("pro unlock mutex fail !");

			switch (mfr_id) {
			case 0:
				/* maybe the board is DVT + XDP710 (addr: 0x28) */
				if (get_pmbus_mfr_id(p->port, dvt_xdp_addr)) {
					p->type = sensor_dev_xdp710;
					p->target_addr = dvt_xdp_addr;
					p->init_args = xdp_init_arr;
				}

				break;
			case XDP710_MFR_ID:
				p->type = sensor_dev_xdp710;
				p->target_addr = dvt_xdp_addr;
				p->init_args = xdp_init_arr;

				break;
			default:
				break;
			}
		}
	}
}

void load_hsc_sensor_config()
{
	/* identify hsc module */
	hsc_config(HSC_CONFIG_FB);
	hsc_config(HSC_CONFIG_BPB);
	hsc_config(HSC_CONFIG_BB);

	for (uint8_t i = 0; i < ARRAY_SIZE(hsc_sensor_config_table); i++)
		add_sensor_config(hsc_sensor_config_table[i]);
}

void load_sb_temp_sensor_with_main_and_2nd_config()
{
	/* default sensor config is tmp461
	 * 1st and 2nd source have different i2c addr, identify by i2c addr
	*/
#define TMP461_MFR_ID_OFFSET 0xFE
#define NCT214_MFR_ID_OFFSET 0xFE
#define TMP461_MFR_ID 0x55
#define NCT214_MFR_ID 0x41

	uint8_t temp_mfr_id = 0;
	for (uint8_t i = 0; i < ARRAY_SIZE(tmp421_config_table); i++) {
		temp_mfr_id = get_temp_sensor_mfr_id(tmp421_config_table[i].port,
						     tmp421_config_table[i].target_addr,
						     TMP461_MFR_ID_OFFSET);
		if (temp_mfr_id == TMP461_MFR_ID) {
			add_sensor_config(tmp421_config_table[i]);
			LOG_INF("Add tmp461 %d address on sensorboard ok: 0x%x", i,
				tmp421_config_table[i].target_addr);
			continue;
		} else {
			LOG_INF("Can't read MFR_ID from 0x%x TMP461 , try to read NCT214_MFR_ID",
				tmp421_config_table[i].target_addr);
			temp_mfr_id = get_temp_sensor_mfr_id(nct214_config_table[i].port,
							     nct214_config_table[i].target_addr,
							     NCT214_MFR_ID_OFFSET);
		}

		if (temp_mfr_id == NCT214_MFR_ID) {
			add_sensor_config(nct214_config_table[i]);
			LOG_INF("Add nct214 %d address on sensorboard ok: 0x%x", i,
				nct214_config_table[i].target_addr);
		} else {
			LOG_ERR("Can't read MFR_ID from 0x%x NCT214, load temperature sensor on sensor board failed",
				nct214_config_table[i].target_addr);
			// still add sensor config to keep SENSOR_CONFIG_SIZE correct
			add_sensor_config(tmp421_config_table[i]);
		}
	}
}
void load_sb_temp_sensor_config()
{
#define TMP421_MFR_ID 0x55
#define TMP421_MFR_ID_OFFSET 0xFE

	uint8_t index = 0;

	if (!pre_PCA9546A_read(&tmp421_config_table[0], &bus_9_PCA9546A_configs[0]))
		LOG_ERR("pre lock mutex fail !");

	for (index = 0; index < ARRAY_SIZE(tmp421_config_table); index++) {
		uint8_t retry = 5;
		I2C_MSG msg;
		msg.bus = tmp421_config_table[index].port;
		msg.target_addr = tmp421_config_table[index].target_addr;
		msg.tx_len = 1;
		msg.rx_len = 1;
		uint8_t mfr_id;
		msg.data[0] = TMP421_MFR_ID_OFFSET;

		if (i2c_master_read(&msg, retry)) {
			LOG_ERR("Failed to read Sensor board tmp421 module MFR_ID, try to access nct214.");
		}

		mfr_id = msg.data[0];
		LOG_INF("Sensor board temp module 0x%x mfr_id: %x\n",
			tmp421_config_table[index].num, mfr_id);

		if (mfr_id == TMP421_MFR_ID)
			add_sensor_config(tmp421_config_table[index]);
		else
			add_sensor_config(nct214_config_table[index]);
	}

	if (!post_PCA9546A_read(&tmp421_config_table[0], &bus_9_PCA9546A_configs[0], 0))
		LOG_ERR("pro unlock mutex fail !");
}
void load_plat_def_sensor_config()
{
	uint8_t index = 0;

	for (index = 0; index < ARRAY_SIZE(plat_def_sensor_config); index++)
		add_sensor_config(plat_def_sensor_config[index]);
}

static void change_dvt_sensor_config()
{
	uint8_t stage = 0;
	stage = get_board_stage();
	LOG_WRN("board stage: %d", stage);

	if (stage == BOARD_STAGE_EVT)
		return;

	for (uint8_t i = 0; i < ARRAY_SIZE(plat_sensor_config); i++) {
		sensor_cfg *p = plat_sensor_config + i;
		switch (p->num) {
		case SENSOR_NUM_MB_RPU_AIR_INLET_TEMP_C:
			p->type = sensor_dev_tmp75;
			p->offset = TMP75_TEMP_OFFSET;
			p->target_addr = FIO_TMP75_ADDR;
			p->init_args = NULL;
			break;
		case SENSOR_NUM_FB_1_FAN_TACH_RPM:
		case SENSOR_NUM_FB_2_FAN_TACH_RPM:
		case SENSOR_NUM_FB_3_FAN_TACH_RPM:
		case SENSOR_NUM_FB_4_FAN_TACH_RPM:
		case SENSOR_NUM_FB_5_FAN_TACH_RPM:
		case SENSOR_NUM_FB_6_FAN_TACH_RPM:
		case SENSOR_NUM_FB_7_FAN_TACH_RPM:
		case SENSOR_NUM_FB_8_FAN_TACH_RPM:
		case SENSOR_NUM_FB_9_FAN_TACH_RPM:
		case SENSOR_NUM_FB_10_FAN_TACH_RPM:
		case SENSOR_NUM_FB_11_FAN_TACH_RPM:
		case SENSOR_NUM_FB_12_FAN_TACH_RPM:
		case SENSOR_NUM_FB_13_FAN_TACH_RPM:
		case SENSOR_NUM_FB_14_FAN_TACH_RPM:
			p->arg0 = NCT7363_16_PORT;
			// disable alert blink
			if (!nct7363_write(p, NCT7363_GPIO03_GPIO07_ALERT_LED_REG_OFFSET, 0))
				LOG_INF("Write fan_board_fault pwm fail\n");
			break;
		}
	}

	for (uint8_t i = 0; i < SIZEOF_NCT7363_INIT_ARGS; i++) {
		nct7363_init_arg *f = nct7363_init_args + i;
		/*
			change fan board hook config 
			Modify :
				pwrgd_fan from port10 to port04, 
				fault_fan from port11 to port08
			Add :
				tach2 in port16
		*/
		if (i < 14) {
			// gpio out
			f->pin_type[NCT7363_10_PORT] = NCT7363_PIN_TPYE_GPIO;
			f->pin_type[NCT7363_11_PORT] = NCT7363_PIN_TPYE_GPIO;
			f->gpio_10 = 0;

			//pwrgd pin type
			f->pin_type[NCT7363_4_PORT] = NCT7363_PIN_TPYE_GPIO_DEFAULT_OUTPUT;
			f->gpio_03 = 1; //gpio out default value (active low)

			// fanin pin type
			f->pin_type[NCT7363_16_PORT] = NCT7363_PIN_TPYE_FANIN;
			// fanin setting
			f->threshold[NCT7363_16_PORT] = 50;
			f->fan_poles[NCT7363_16_PORT] = 4;

			// fault pin type
			f->pin_type[NCT7363_8_PORT] = NCT7363_PIN_TPYE_GPIO_DEFAULT_OUTPUT;
			f->gpio_07 = 0;
		}
		/*
			change pump board hook config
			Modify: 
				pwrgd_pump from port10 to port08
				fault_pump from port11 to port13
		*/
		else if (i < 17) {
			f->pin_type[NCT7363_10_PORT] = 0;
			f->gpio_10 = 0;
			f->pin_type[NCT7363_8_PORT] = NCT7363_PIN_TPYE_GPIO_DEFAULT_OUTPUT;
			f->gpio_07 = 1;

			f->pin_type[NCT7363_11_PORT] = 0;
			f->gpio_11 = 0;
			f->pin_type[NCT7363_13_PORT] = NCT7363_PIN_TPYE_GPIO_DEFAULT_OUTPUT;
			f->gpio_13 = 0;
		}
		// backplane add level sensor 3
		else {
			//do nothing because pin type default is gpio input
			LOG_INF("level sensor 3 config ok, no need to changed");
		}
	}
}

static void change_brick_sensor_config()
{
#define E50SN12051_MFR_ID 0x0644
#define BMR4922302_803_MFR_ID 0x0c46

	uint8_t retry = 5;
	I2C_MSG msg;
	msg.bus = I2C_BUS4;
	msg.target_addr = BPB_BRICK_12V_ADDR;
	msg.tx_len = 1;
	msg.rx_len = 4;
	uint16_t mfr_id;
	msg.data[0] = PMBUS_MFR_ID;

	if (i2c_master_read(&msg, retry)) {
		LOG_ERR("Failed to read Brick module MFR_ID");
		return;
	}

	mfr_id = (msg.data[0] << 8) | msg.data[1];
	LOG_INF("Brick module mfr_id: %x\n", mfr_id);

	if (mfr_id == E50SN12051_MFR_ID)
		return;

	for (uint8_t i = 0; i < ARRAY_SIZE(plat_sensor_config); i++) {
		sensor_cfg *p = plat_sensor_config + i;
		if (p->num == SENSOR_NUM_BPB_BRICK_12V_VIN_VOLT_V ||
		    p->num == SENSOR_NUM_BPB_BRICK_12V_VOUT_VOLT_V ||
		    p->num == SENSOR_NUM_BPB_BRICK_12V_IOUT_CURR_A ||
		    p->num == SENSOR_NUM_BPB_BRICK_12V_TEMP_C) {
			p->type = sensor_dev_bmr4922302_803;
			p->init_args = &bmr4922302_803_init_args[0];
		}
	}
}

static void check_pdb_u15_2nd_src_config()
{
	uint8_t retry = 5;
	I2C_MSG msg;
	msg.bus = I2C_BUS9;
	msg.target_addr = PDB_INA238_U15_ADDR;
	msg.tx_len = 1;
	msg.rx_len = 1;

	sensor_cfg PDB_U15_config[] = {
		{ SENSOR_NUM_PDB_48V_SENSE_DIFF_NEG_VOLT_V, sensor_dev_ina238, I2C_BUS9,
		  PDB_INA238_U15_ADDR, INA238_VSHUNT_OFFSET, stby_access, 0, 0,
		  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
		  SENSOR_INIT_STATUS, pre_PCA9546A_read, &bus_9_PCA9546A_configs[1],
		  post_PCA9546A_read, NULL, &ina238_init_args[1] },
	};

	if (!pre_PCA9546A_read(&PDB_U15_config[0], &bus_9_PCA9546A_configs[1]))
		LOG_ERR("pre lock mutex fail !");

	if (i2c_master_read(&msg, retry)) {
		LOG_ERR("Failed to read PDB U14 ADC ina238, check 2nd src U99");
		for (uint8_t i = 0; i < ARRAY_SIZE(plat_sensor_config); i++) {
			sensor_cfg *p = plat_sensor_config + i;
			if (p->num == SENSOR_NUM_PDB_48V_SENSE_DIFF_NEG_VOLT_V) {
				p->type = sensor_dev_max11617;
				p->target_addr = PDB_MAX11617_U99_ADDR;
				p->offset = 0;
				p->init_args = &max11617_init_args[0];
			}
		}
	}

	if (!post_PCA9546A_read(&PDB_U15_config[0], &bus_9_PCA9546A_configs[1], 0))
		LOG_ERR("pro unlock mutex fail !");
}
void load_sensor_config(void)
{
	change_dvt_sensor_config();
	change_brick_sensor_config();
	check_pdb_u15_2nd_src_config();
	memcpy(sensor_config, plat_sensor_config, sizeof(plat_sensor_config));
	sensor_config_count = ARRAY_SIZE(plat_sensor_config);

	load_hsc_sensor_config();
	load_sb_temp_sensor_config();
	load_plat_def_sensor_config();
}

uint16_t get_sensor_reading_to_modbus_val(uint8_t sensor_num, int8_t exp, int8_t scale)
{
	int reading = 0;
	uint8_t status = get_sensor_reading(sensor_config, sensor_config_count, sensor_num,
					    &reading, GET_FROM_CACHE);

	if (status != SENSOR_READ_4BYTE_ACUR_SUCCESS) {
		LOG_ERR("0x%02x get sensor cache fail", sensor_num);
		return 0;
	}
	const sensor_val *sval = (sensor_val *)&reading;
	float val = (sval->integer * 1000 + sval->fraction) / 1000;
	float r = pow_of_10(exp);
	return val / scale / r; // scale
}

/*
	get real float val from sensor cache
	return sensor status
*/
uint8_t get_sensor_reading_to_real_val(uint8_t sensor_num, float *val)
{
	CHECK_NULL_ARG_WITH_RETURN(val, SENSOR_PARAMETER_NOT_VALID);

	int reading = 0;
	uint8_t status = get_sensor_reading(sensor_config, sensor_config_count, sensor_num,
					    &reading, GET_FROM_CACHE);

	if (status != SENSOR_READ_4BYTE_ACUR_SUCCESS) {
		LOG_ERR("0x%02x get sensor cache fail", sensor_num);
		return status;
	}

	const sensor_val *sval = (sensor_val *)&reading;
	*val = (sval->integer * 1000 + sval->fraction) / 1000.0;

	return status;
}

/* switch mux from sensor cfg*/
bool switch_sensor_mux(sensor_cfg *cfg)
{
	CHECK_NULL_ARG_WITH_RETURN(cfg, false);

	if ((cfg->pre_sensor_read_hook)) {
		if ((cfg->pre_sensor_read_hook)(cfg, cfg->pre_sensor_read_args) == false) {
			LOG_DBG("read value pre lock mutex fail !");
			return false;
		}
	}

	if ((cfg->post_sensor_read_hook)) {
		if ((cfg->post_sensor_read_hook)(cfg, cfg->post_sensor_read_args, 0) == false) {
			LOG_DBG("read value post lock mutex fail !");
			return false;
		}
	}

	return true;
}

/* platform def sensor */
static uint8_t plat_sensor_rpu_pwr[] = {
	SENSOR_NUM_BB_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_BPB_HSC_P48V_PIN_PWR_W,
};

static uint8_t plat_sensor_hex_pwr[] = {
	SENSOR_NUM_FB_1_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_2_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_3_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_4_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_5_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_6_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_7_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_8_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_9_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_10_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_11_HSC_P48V_PIN_PWR_W, SENSOR_NUM_FB_12_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_13_HSC_P48V_PIN_PWR_W, SENSOR_NUM_FB_14_HSC_P48V_PIN_PWR_W,
};

static uint8_t plat_sensor_hex_curr[] = {
	SENSOR_NUM_FB_1_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_2_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_3_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_4_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_5_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_6_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_7_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_8_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_9_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_10_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_11_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_FB_12_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_13_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_FB_14_HSC_P48V_IOUT_CURR_A,
};

static uint8_t plat_sensor_sb_hex_air_inlet_temp[] = {
	SENSOR_NUM_SB_HEX_AIR_INLET_1_TEMP_C,
	SENSOR_NUM_SB_HEX_AIR_INLET_2_TEMP_C,
	SENSOR_NUM_SB_HEX_AIR_INLET_3_TEMP_C,
	SENSOR_NUM_SB_HEX_AIR_INLET_4_TEMP_C,
};

/* Sum the values in the sensor cache in the array */
static float calculate_total_val(uint8_t arr[], uint8_t size)
{
	CHECK_NULL_ARG_WITH_RETURN(arr, 0);

	float total = 0;
	for (uint8_t i = 0; i < size; i++) {
		float tmp = 0;
		const sensor_cfg *cfg = get_common_sensor_cfg_info(arr[i]);
		if (cfg->cache_status != SENSOR_READ_4BYTE_ACUR_SUCCESS)
			continue;
		if (get_sensor_reading_to_real_val(arr[i], &tmp) == SENSOR_READ_4BYTE_ACUR_SUCCESS)
			total += tmp;
	}

	return total;
}

/* pressure difference  */
static float pressure_difference_val(uint8_t high_press, uint8_t low_press)
{
	float high = 0, low = 0;

	if (get_sensor_reading_to_real_val(high_press, &high) != SENSOR_READ_4BYTE_ACUR_SUCCESS)
		return 0;

	if (get_sensor_reading_to_real_val(low_press, &low) != SENSOR_READ_4BYTE_ACUR_SUCCESS)
		return 0;

	return (high - low);
}

static uint8_t sb_hex_air_inlet_temp_avg(void)
{
	uint8_t number = 0;
	float total = 0;
	for (uint8_t i = 0; i < ARRAY_SIZE(plat_sensor_sb_hex_air_inlet_temp); i++) {
		float tmp = 0;
		if (get_sensor_reading_to_real_val(plat_sensor_sb_hex_air_inlet_temp[i], &tmp) ==
		    SENSOR_READ_4BYTE_ACUR_SUCCESS) {
			/* only calculate values without exceptions */
			if ((tmp > -20) && (tmp < 100)) {
				total += tmp;
				number++;
			}
		}
	}

	return (number ? (total / number) : 0);
}

static bool aalc_cooling_capacity(float *val)
{
	/*
	*	AALC_Cooling_Capacity_kW  = 67.21*Flow rate*(Tout-Tin)
	*	Flow Rate = Flow sensor reading (LPM)
	*	Tout = Rack Coolant temperature sensor reading (°C)
	*	Tin = RPU Coolant outlet temperature sensor reading(°C)
	*/

	float flow_rate_val, tout_val, tin_val;

	uint8_t flow_rate_status = get_sensor_reading_to_real_val(
		SENSOR_NUM_BPB_RPU_COOLANT_FLOW_RATE_LPM, &flow_rate_val);
	uint8_t tout_status =
		get_sensor_reading_to_real_val(SENSOR_NUM_BPB_HEX_WATER_INLET_TEMP_C, &tout_val);
	uint8_t tin_status =
		get_sensor_reading_to_real_val(SENSOR_NUM_BPB_RPU_COOLANT_INLET_TEMP_C, &tin_val);

	if (flow_rate_status != SENSOR_READ_4BYTE_ACUR_SUCCESS)
		return false;

	if (tout_status != SENSOR_READ_4BYTE_ACUR_SUCCESS)
		return false;

	if (tin_status != SENSOR_READ_4BYTE_ACUR_SUCCESS)
		return false;

	*val = 0.06721 * flow_rate_val * (tout_val - tin_val);
	if (*val < 0)
		*val = 0;

	return true;
}

static uint8_t plat_def_sensor_read(sensor_cfg *cfg, int *reading)
{
	CHECK_NULL_ARG_WITH_RETURN(cfg, SENSOR_UNSPECIFIED_ERROR);
	CHECK_NULL_ARG_WITH_RETURN(reading, SENSOR_UNSPECIFIED_ERROR);

	uint8_t type = cfg->offset;

	float val = 0;
	switch (type) {
	case PLAT_DEF_SENSOR_RPU_PWR:
		val = calculate_total_val(plat_sensor_rpu_pwr, ARRAY_SIZE(plat_sensor_rpu_pwr));
		break;
	case PLAT_DEF_SENSOR_HEX_PWR:
		val = calculate_total_val(plat_sensor_hex_pwr, ARRAY_SIZE(plat_sensor_hex_pwr));
		break;
	case PLAT_DEF_SENSOR_TOTAL_PWR:
		val = calculate_total_val(plat_sensor_rpu_pwr, ARRAY_SIZE(plat_sensor_rpu_pwr));
		val += calculate_total_val(plat_sensor_hex_pwr, ARRAY_SIZE(plat_sensor_hex_pwr));
		break;
	case PLAT_DEF_SENSOR_HEX_CURR:
		val = calculate_total_val(plat_sensor_hex_curr, ARRAY_SIZE(plat_sensor_hex_curr));
		break;
	case PLAT_DEF_SENSOR_HEX_EXTERNAL_Y_FILTER:
		val = pressure_difference_val(SENSOR_NUM_BPB_RACK_PRESSURE_3_P_KPA,
					      SENSOR_NUM_BPB_RACK_PRESSURE_4_P_KPA);
		// convert to absolute value in EVT and DVT stages
		if (((get_board_stage() == BOARD_STAGE_EVT) ||
		     (get_board_stage() == BOARD_STAGE_DVT)) &&
		    (val < 0))
			val = -val;
		break;
	case PLAT_DEF_SENSOR_FAN_PRSNT: {
		uint16_t tmp_prsnt = 0;
		get_fb_present_status(&tmp_prsnt);

		sensor_val *sval = (sensor_val *)reading;
		sval->integer = tmp_prsnt;
		return SENSOR_READ_SUCCESS;
	}
	case PLAT_DEF_SENSOR_SB_HEX_AIR_INLET_AVG_TEMP: {
		val = sb_hex_air_inlet_temp_avg();
		break;
	}
	case PLAT_DEF_SENSOR_COOLING_CAPACITY: {
		if (!aalc_cooling_capacity(&val))
			return SENSOR_FAIL_TO_ACCESS;
		break;
	}
	default:
		LOG_ERR("0x%02x unknow plat sensor type %d", cfg->num, type);
		return SENSOR_PARAMETER_NOT_VALID;
	}

	sensor_val *sval = (sensor_val *)reading;
	sval->integer = (int)val & 0xFFFF;
	sval->fraction = (val - sval->integer) * 1000;

	return SENSOR_READ_SUCCESS;
}

uint8_t plat_def_sensor_init(sensor_cfg *cfg)
{
	CHECK_NULL_ARG_WITH_RETURN(cfg, SENSOR_INIT_UNSPECIFIED_ERROR);

	cfg->read = plat_def_sensor_read;
	return SENSOR_INIT_SUCCESS;
}
