/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "plat_sensor_table.h"
#include <stdio.h>
#include <string.h>
#include "plat_i2c.h"
#include "sensor.h"
#include "ast_adc.h"
#include "plat_hook.h"
#include "plat_class.h"
#include "plat_modbus.h"
#include "plat_util.h"
#include "modbus_server.h"
#include <logging/log.h>

LOG_MODULE_REGISTER(plat_sensor_table);

#define I2C_MAX_RETRY 3

sensor_cfg plat_sensor_config[] = {
	/* number,                  type,       port,      address,      offset,
	   access check, arg0, arg1, sample_count, cache, cache_status, mux_address, mux_offset,
	   pre_sensor_read_fn, pre_sensor_read_args, post_sensor_read_fn, post_sensor_read_args  */
	{ SENSOR_NUM_FB_1_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[0] },
	{ SENSOR_NUM_FB_2_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[1] },
	{ SENSOR_NUM_FB_3_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[2] },
	{ SENSOR_NUM_FB_4_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, NULL, &nct7363_init_args[3] },
	{ SENSOR_NUM_FB_5_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[4] },
	{ SENSOR_NUM_FB_6_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[5] },
	{ SENSOR_NUM_FB_7_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[6] },
	{ SENSOR_NUM_FB_8_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[3], post_PCA9546A_read, NULL, &nct7363_init_args[7] },
	{ SENSOR_NUM_FB_9_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[8] },
	{ SENSOR_NUM_FB_10_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[9] },
	{ SENSOR_NUM_FB_11_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[10] },
	{ SENSOR_NUM_FB_12_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &nct7363_init_args[11] },
	{ SENSOR_NUM_FB_13_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS7, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[12] },
	{ SENSOR_NUM_FB_14_FAN_TACH_RPM, sensor_dev_nct7363, I2C_BUS7, FB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_15_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[13] },
	{ SENSOR_NUM_PB_1_PUMP_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[14] },
	{ SENSOR_NUM_PB_1_FAN_1_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[14] },
	{ SENSOR_NUM_PB_1_FAN_2_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_7_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct7363_init_args[14] },
	{ SENSOR_NUM_PB_2_PUMP_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[15] },
	{ SENSOR_NUM_PB_2_FAN_1_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[15] },
	{ SENSOR_NUM_PB_2_FAN_2_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_7_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &nct7363_init_args[15] },
	{ SENSOR_NUM_PB_3_PUMP_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[16] },
	{ SENSOR_NUM_PB_3_FAN_1_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[16] },
	{ SENSOR_NUM_PB_3_FAN_2_TACH_RPM, sensor_dev_nct7363, I2C_BUS8, PB_NCT7363_ADDR,
	  NCT7363_FAN_SPEED_OFFSET, stby_access, NCT7363_7_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &nct7363_init_args[16] },
	{ SENSOR_NUM_MB_FAN1_TACH_RPM, sensor_dev_ast_tach, TACH_PORT0, NONE, AST_TACH_RPM,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_MB_FAN2_TACH_RPM, sensor_dev_ast_tach, TACH_PORT1, NONE, AST_TACH_RPM,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_BPB_RACK_LEVEL_1, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR,
	  NCT7363_GPIO_READ_OFFSET, stby_access, NCT7363_5_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &nct7363_init_args[17] },
	{ SENSOR_NUM_BPB_RACK_LEVEL_2, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR,
	  NCT7363_GPIO_READ_OFFSET, stby_access, NCT7363_6_PORT, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &nct7363_init_args[17] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_INLET_P_KPA, sensor_dev_ads112c, I2C_BUS9, SB_ADS112C_1_ADDR,
	  ADS112C_PRESS_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_ads112c_read, NULL, &ads112c_init_args[1] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_OUTLET_P_KPA, sensor_dev_ads112c, I2C_BUS9, SB_ADS112C_1_ADDR,
	  ADS112C_PRESS_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_ads112c_read, NULL, &ads112c_init_args[2] },
	{ SENSOR_NUM_BPB_RACK_PRESSURE_3_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_PRESS_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read, NULL,
	  &ads112c_init_args[1] },
	{ SENSOR_NUM_BPB_RACK_PRESSURE_4_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_PRESS_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read, NULL,
	  &ads112c_init_args[2] },
	{ SENSOR_NUM_SB_HEX_PRESSURE_1_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_PRESS_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read, NULL,
	  &ads112c_init_args[3] },
	{ SENSOR_NUM_SB_HEX_PRESSURE_2_P_KPA, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR,
	  ADS112C_PRESS_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read, NULL,
	  &ads112c_init_args[4] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_FLOW_RATE_LPM, sensor_dev_ads112c, I2C_BUS5,
	  BPB_ADS112C_4_ADDR, ADS112C_FLOW_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, NULL, &ads112c_init_args[5] },
	{ SENSOR_NUM_FB_1_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[0] },
	{ SENSOR_NUM_FB_2_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_1_PCA9546A_configs[1], NULL,
	  NULL, &hdc1080_init_args[1] },
	{ SENSOR_NUM_FB_3_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_1_PCA9546A_configs[2], NULL,
	  NULL, &hdc1080_init_args[2] },
	{ SENSOR_NUM_FB_4_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_1_PCA9546A_configs[3], NULL,
	  NULL, &hdc1080_init_args[3] },
	{ SENSOR_NUM_FB_5_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_2_PCA9546A_configs[0], NULL,
	  NULL, &hdc1080_init_args[4] },
	{ SENSOR_NUM_FB_6_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_2_PCA9546A_configs[1], NULL,
	  NULL, &hdc1080_init_args[5] },
	{ SENSOR_NUM_FB_7_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_2_PCA9546A_configs[2], NULL,
	  NULL, &hdc1080_init_args[6] },
	{ SENSOR_NUM_FB_8_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_2_PCA9546A_configs[3], NULL,
	  NULL, &hdc1080_init_args[7] },
	{ SENSOR_NUM_FB_9_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_6_PCA9546A_configs[0], NULL,
	  NULL, &hdc1080_init_args[8] },
	{ SENSOR_NUM_FB_10_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_6_PCA9546A_configs[1], NULL,
	  NULL, &hdc1080_init_args[9] },
	{ SENSOR_NUM_FB_11_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_6_PCA9546A_configs[2], NULL,
	  NULL, &hdc1080_init_args[10] },
	{ SENSOR_NUM_FB_12_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_6_PCA9546A_configs[3], NULL,
	  NULL, &hdc1080_init_args[11] },
	{ SENSOR_NUM_FB_13_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_7_PCA9546A_configs[0], NULL,
	  NULL, &hdc1080_init_args[12] },
	{ SENSOR_NUM_FB_14_HEX_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_7_PCA9546A_configs[1], NULL,
	  NULL, &hdc1080_init_args[13] },
	{ SENSOR_NUM_PB_1_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_8_PCA9546A_configs[0], NULL,
	  NULL, &hdc1080_init_args[14] },
	{ SENSOR_NUM_PB_2_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_8_PCA9546A_configs[1], NULL,
	  NULL, &hdc1080_init_args[15] },
	{ SENSOR_NUM_PB_3_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, &bus_8_PCA9546A_configs[2], NULL,
	  NULL, &hdc1080_init_args[16] },
	{ SENSOR_NUM_BB_TMP75_TEMP_C, sensor_dev_tmp75, I2C_BUS4, BB_TMP75_ADDR, TMP75_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_BPB_RPU_OUTLET_TEMP_C, sensor_dev_tmp75, I2C_BUS4, BPB_TMP75_ADDR,
	  TMP75_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_BPB_RPU_COOLANT_INLET_TEMP_C, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_1_ADDR,
	  ADS112C_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read, NULL,
	  &ads112c_init_args[6] },
	{ SENSOR_NUM_BPB_RPU_COOLANT_OUTLET_TEMP_C, sensor_dev_ads112c, I2C_BUS3,
	  BPB_ADS112C_2_ADDR, ADS112C_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL,
	  post_ads112c_read, NULL, &ads112c_init_args[6] },
	{ SENSOR_NUM_BPB_HEX_WATER_INLET_TEMP_C, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_3_ADDR,
	  ADS112C_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_ads112c_read, NULL,
	  &ads112c_init_args[6] },
	{ SENSOR_NUM_MB_RPU_AIR_INLET_TEMP_C, sensor_dev_hdc1080, I2C_BUS10, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &hdc1080_init_args[17] },
	{ SENSOR_NUM_PDB_HDC1080DMBR_TEMP_C, sensor_dev_hdc1080, I2C_BUS9, HDC1080_ADDR,
	  HDC1080_TEMP_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[18] },
	{ SENSOR_NUM_FB_1_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[0] },
	{ SENSOR_NUM_FB_2_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[1] },
	{ SENSOR_NUM_FB_3_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[2] },
	{ SENSOR_NUM_FB_4_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, NULL, &hdc1080_init_args[3] },
	{ SENSOR_NUM_FB_5_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[4] },
	{ SENSOR_NUM_FB_6_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[5] },
	{ SENSOR_NUM_FB_7_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[6] },
	{ SENSOR_NUM_FB_8_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[3], post_PCA9546A_read, NULL, &hdc1080_init_args[7] },
	{ SENSOR_NUM_FB_9_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[8] },
	{ SENSOR_NUM_FB_10_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[9] },
	{ SENSOR_NUM_FB_11_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[10] },
	{ SENSOR_NUM_FB_12_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &hdc1080_init_args[11] },
	{ SENSOR_NUM_FB_13_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[12] },
	{ SENSOR_NUM_FB_14_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[13] },
	{ SENSOR_NUM_MB_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS10, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &hdc1080_init_args[17] },
	{ SENSOR_NUM_PDB_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS9, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, pre_PCA9546A_read, &bus_9_PCA9546A_configs[1], post_PCA9546A_read,
	  NULL, &hdc1080_init_args[18] },
	{ SENSOR_NUM_PB_1_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &hdc1080_init_args[14] },
	{ SENSOR_NUM_PB_2_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &hdc1080_init_args[15] },
	{ SENSOR_NUM_PB_3_HUM_PCT_RH, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR,
	  HDC1080_HUM_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &hdc1080_init_args[16] },
	{ SENSOR_NUM_BPB_CDU_COOLANT_LEAKAGE_VOLT_V, sensor_dev_ads112c, I2C_BUS5,
	  BPB_ADS112C_1_ADDR, ADS112C_LEAKAGE_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ads112c_init_args[0] },
	{ SENSOR_NUM_BPB_RACK_COOLANT_LEAKAGE_VOLT_V, sensor_dev_ads112c, I2C_BUS5,
	  BPB_ADS112C_3_ADDR, ADS112C_LEAKAGE_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &ads112c_init_args[0] },
	{ SENSOR_NUM_SB_TTV_COOLANT_LEAKAGE_1_VOLT_V, sensor_dev_ads112c, I2C_BUS9,
	  SB_ADS112C_2_ADDR, ADS112C_LEAKAGE_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &ads112c_init_args[0] },
	{ SENSOR_NUM_SB_TTV_COOLANT_LEAKAGE_2_VOLT_V, sensor_dev_ads112c, I2C_BUS9,
	  SB_ADS112C_2_ADDR, ADS112C_LEAKAGE_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &ads112c_init_args[0] },
	{ SENSOR_NUM_SB_TTV_COOLANT_LEAKAGE_3_VOLT_V, sensor_dev_ads112c, I2C_BUS9,
	  SB_ADS112C_3_ADDR, ADS112C_LEAKAGE_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &ads112c_init_args[0] },
	// ADC
	{ SENSOR_NUM_V_12_AUX, sensor_dev_ast_adc, ADC_PORT0, NONE, NONE, dc_access, 676, 100,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_5_AUX, sensor_dev_ast_adc, ADC_PORT1, NONE, NONE, dc_access, 711, 200,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_3_3_AUX, sensor_dev_ast_adc, ADC_PORT2, NONE, NONE, dc_access, 2, 1,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_1_2_AUX, sensor_dev_ast_adc, ADC_PORT3, NONE, NONE, dc_access, 1, 1,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },
	{ SENSOR_NUM_V_5_USB, sensor_dev_ast_adc, ADC_PORT4, NONE, NONE, dc_access, 711, 200,
	  SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS,
	  NULL, NULL, NULL, NULL, &adc_asd_init_args[0] },

	// PDB sense differential voltages
	{ SENSOR_NUM_PDB_48V_SENSE_DIFF_POS_VOLT_V, sensor_dev_ina238, I2C_BUS9,
	  PDB_INA238_U14_ADDR, INA238_VSHUNT_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[1], post_PCA9546A_read, NULL, NULL },
	{ SENSOR_NUM_PDB_48V_SENSE_DIFF_NEG_VOLT_V, sensor_dev_ina238, I2C_BUS9,
	  PDB_INA238_U15_ADDR, INA238_VSHUNT_OFFSET, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT,
	  POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[1], post_PCA9546A_read, NULL, NULL },
};

sensor_cfg hsc_sensor_config_table[] = {
	{ SENSOR_NUM_FB_1_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_1_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_1_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_1_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[0] },
	{ SENSOR_NUM_FB_2_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_2_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_2_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_2_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[1] },
	{ SENSOR_NUM_FB_3_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_3_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_3_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_3_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[2] },
	{ SENSOR_NUM_FB_4_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, NULL, &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_4_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, NULL, &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_4_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_4_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS1, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_1_PCA9546A_configs[3], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[3] },
	{ SENSOR_NUM_FB_5_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_5_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_5_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_5_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[4] },
	{ SENSOR_NUM_FB_6_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_6_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_6_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_6_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[5] },
	{ SENSOR_NUM_FB_7_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_7_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_7_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_7_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[6] },
	{ SENSOR_NUM_FB_8_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[3], post_PCA9546A_read, NULL, &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_8_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[3], post_PCA9546A_read, NULL, &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_8_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[3], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_8_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS2, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_2_PCA9546A_configs[3], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[7] },
	{ SENSOR_NUM_FB_9_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_9_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_9_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_9_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[8] },
	{ SENSOR_NUM_FB_10_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_10_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_10_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_10_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[9] },
	{ SENSOR_NUM_FB_11_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_11_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_11_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_11_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[10] },
	{ SENSOR_NUM_FB_12_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_12_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_12_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_VOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, NULL, &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_12_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS6, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_6_PCA9546A_configs[3], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[11] },
	{ SENSOR_NUM_FB_13_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_13_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_13_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_13_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[12] },
	{ SENSOR_NUM_FB_14_HSC_TEMP_C, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[13] },
	{ SENSOR_NUM_FB_14_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[13] },
	{ SENSOR_NUM_FB_14_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[13] },
	{ SENSOR_NUM_FB_14_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS7, FB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_7_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[13] },
	{ SENSOR_NUM_PB_1_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_1_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, NULL, &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_1_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_1_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[0], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[14] },
	{ SENSOR_NUM_PB_2_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_2_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, NULL, &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_2_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_2_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[1], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[15] },
	{ SENSOR_NUM_PB_3_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[16] },
	{ SENSOR_NUM_PB_3_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, NULL, &adm1272_init_args[16] },
	{ SENSOR_NUM_PB_3_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[16] },
	{ SENSOR_NUM_PB_3_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS8, PB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_8_PCA9546A_configs[2], post_PCA9546A_read, post_adm1272_read,
	  &adm1272_init_args[16] },
	{ SENSOR_NUM_BB_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BB_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BB_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BB_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[17] },
	{ SENSOR_NUM_BPB_HSC_P48V_TEMP_C, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[18] },
	{ SENSOR_NUM_BPB_HSC_P48V_VIN_VOLT_V, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_VIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[18] },
	{ SENSOR_NUM_BPB_HSC_P48V_IOUT_CURR_A, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_IOUT, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[18] },
	{ SENSOR_NUM_BPB_HSC_P48V_PIN_PWR_W, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_PIN, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL,
	  &adm1272_init_args[18] },
};
sensor_cfg tmp461_config_table[] = {
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_1_TEMP_C, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_1_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_2_TEMP_C, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_2_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_3_TEMP_C, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_3_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_4_TEMP_C, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_4_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, NULL },
};
sensor_cfg nct214_config_table[] = {
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_1_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_1_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[0] },
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_2_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_2_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[1] },
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_3_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_3_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[2] },
	{ SENSOR_NUM_SB_HEX_AIR_OUTLET_4_TEMP_C, sensor_dev_nct214, I2C_BUS9, SB_NCT214_4_ADDR,
	  NCT214_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, pre_PCA9546A_read,
	  &bus_9_PCA9546A_configs[0], post_PCA9546A_read, NULL, &nct214_init_args[3] },
};

sensor_cfg plat_def_sensor_config[] = {
	{ SENSOR_NUM_RPU_PWR_W, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_RPU_PWR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HEX_PWR_W, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_HEX_PWR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_AALC_TOTAL_PWR_W, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_TOTAL_PWR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HEX_CURR_A, sensor_dev_plat_def_sensor, 0, 0, PLAT_DEF_SENSOR_HEX_CURR,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
};

// total config size = plat_sensor_config + sensor(main/second sensor) config table
const int SENSOR_CONFIG_SIZE = ARRAY_SIZE(plat_sensor_config) +
			       ARRAY_SIZE(hsc_sensor_config_table) +
			       ARRAY_SIZE(tmp461_config_table) + ARRAY_SIZE(plat_def_sensor_config);

static uint8_t get_temp_sensor_mfr_id(uint8_t bus, uint8_t addr, uint8_t mfr_id_offset)
{
	I2C_MSG msg = { 0 };
	msg.bus = bus;
	msg.target_addr = addr;
	msg.rx_len = 1;
	msg.tx_len = 1;
	msg.data[0] = mfr_id_offset;
	if (i2c_master_read(&msg, I2C_MAX_RETRY)) {
		LOG_ERR("Failed to read TEMP 0x%x module MFR_ID", addr);
		return 0;
	}

	return msg.data[0];
}

static uint32_t get_pmbus_mfr_id(uint8_t bus, uint8_t addr)
{
	I2C_MSG msg = { 0 };
	msg.bus = bus;
	msg.target_addr = addr;
	msg.rx_len = 3;
	msg.tx_len = 1;
	msg.data[0] = PMBUS_MFR_ID;
	if (i2c_master_read(&msg, I2C_MAX_RETRY)) {
		LOG_ERR("Failed to read HSC module MFR_ID");
		return 0;
	}

	return (msg.data[2] << 16) | (msg.data[1] << 8) | msg.data[0];
}

#define HSC_CONFIG_FB 0x00
#define HSC_CONFIG_BPB 0x01
#define HSC_CONFIG_BB 0x02
#define HSC_CONFIG_PB 0x03

static void hsc_config(uint8_t type)
{
	/* default sensor config is adm1272
	 * EVT stage: 1st and 2nd source have same i2c addr, identify by MFR_ID reg
	 * DVT stage: 1st and 2nd source have different i2c addr, identify by i2c addr
	 * Fan Board EVT: 0x22, 		DVT + XDP710: 0x2A
	 * Backplane Board EVT: 0x20, 	DVT + XDP710: 0x28
	 * Pump Board : 0x22, 			XDP710: 0x22
	 * Bridge Board : 0x26, 		XDP710: 0x26 
	 */

#define ADM1272_MFR_ID 0x494441
#define XDP710_MFR_ID 0x004946
#define XDP710_FB_ADDR_DVT 0x2A
#define XDP710_BPB_ADDR_DVT 0x28
#define XDP710_PB_ADDR 0x22
#define XDP710_BB_ADDR 0x26

	uint8_t fb_sen_tbl[] = { SENSOR_NUM_FB_1_HSC_TEMP_C,
				 SENSOR_NUM_FB_1_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_1_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_1_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_2_HSC_TEMP_C,
				 SENSOR_NUM_FB_2_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_2_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_2_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_3_HSC_TEMP_C,
				 SENSOR_NUM_FB_3_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_3_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_3_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_4_HSC_TEMP_C,
				 SENSOR_NUM_FB_4_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_4_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_4_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_5_HSC_TEMP_C,
				 SENSOR_NUM_FB_5_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_5_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_5_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_6_HSC_TEMP_C,
				 SENSOR_NUM_FB_6_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_6_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_6_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_7_HSC_TEMP_C,
				 SENSOR_NUM_FB_7_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_7_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_7_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_8_HSC_TEMP_C,
				 SENSOR_NUM_FB_8_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_8_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_8_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_9_HSC_TEMP_C,
				 SENSOR_NUM_FB_9_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_9_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_9_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_10_HSC_TEMP_C,
				 SENSOR_NUM_FB_10_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_10_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_10_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_11_HSC_TEMP_C,
				 SENSOR_NUM_FB_11_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_11_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_11_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_12_HSC_TEMP_C,
				 SENSOR_NUM_FB_12_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_12_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_12_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_13_HSC_TEMP_C,
				 SENSOR_NUM_FB_13_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_13_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_13_HSC_P48V_PIN_PWR_W,
				 SENSOR_NUM_FB_14_HSC_TEMP_C,
				 SENSOR_NUM_FB_14_HSC_P48V_VIN_VOLT_V,
				 SENSOR_NUM_FB_14_HSC_P48V_IOUT_CURR_A,
				 SENSOR_NUM_FB_14_HSC_P48V_PIN_PWR_W };

	uint8_t bpb_sen_tbl[] = { SENSOR_NUM_BPB_HSC_P48V_TEMP_C,
				  SENSOR_NUM_BPB_HSC_P48V_VIN_VOLT_V,
				  SENSOR_NUM_BPB_HSC_P48V_IOUT_CURR_A,
				  SENSOR_NUM_BPB_HSC_P48V_PIN_PWR_W };

	uint8_t pb_sen_tbl[] = {
		SENSOR_NUM_PB_1_HSC_P48V_TEMP_C,      SENSOR_NUM_PB_1_HSC_P48V_VIN_VOLT_V,
		SENSOR_NUM_PB_1_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_PB_1_HSC_P48V_PIN_PWR_W,
		SENSOR_NUM_PB_2_HSC_P48V_TEMP_C,      SENSOR_NUM_PB_2_HSC_P48V_VIN_VOLT_V,
		SENSOR_NUM_PB_2_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_PB_2_HSC_P48V_PIN_PWR_W,
		SENSOR_NUM_PB_3_HSC_P48V_TEMP_C,      SENSOR_NUM_PB_3_HSC_P48V_VIN_VOLT_V,
		SENSOR_NUM_PB_3_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_PB_3_HSC_P48V_PIN_PWR_W
	};

	uint8_t bb_tbl[] = { SENSOR_NUM_BB_HSC_P48V_TEMP_C, SENSOR_NUM_BB_HSC_P48V_VIN_VOLT_V,
			     SENSOR_NUM_BB_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_BB_HSC_P48V_PIN_PWR_W };

	uint16_t sen_nums = 0;
	uint8_t *sen_tbl = NULL;
	uint8_t dvt_xdp_addr = 0;
	xdp710_init_arg *xdp_init_arr = NULL;
	switch (type) {
	case HSC_CONFIG_FB:
		sen_nums = ARRAY_SIZE(fb_sen_tbl);
		sen_tbl = fb_sen_tbl;
		dvt_xdp_addr = XDP710_FB_ADDR_DVT;
		xdp_init_arr = &xdp710_init_args[0];
		break;
	case HSC_CONFIG_BPB:
		sen_nums = ARRAY_SIZE(bpb_sen_tbl);
		sen_tbl = bpb_sen_tbl;
		dvt_xdp_addr = XDP710_BPB_ADDR_DVT;
		xdp_init_arr = &xdp710_init_args[3];
		break;
	case HSC_CONFIG_PB:
		sen_nums = ARRAY_SIZE(pb_sen_tbl);
		sen_tbl = pb_sen_tbl;
		dvt_xdp_addr = XDP710_PB_ADDR;
		xdp_init_arr = &xdp710_init_args[1];
		break;
	case HSC_CONFIG_BB:
		sen_nums = ARRAY_SIZE(bb_tbl);
		sen_tbl = bb_tbl;
		dvt_xdp_addr = XDP710_BB_ADDR;
		xdp_init_arr = &xdp710_init_args[2];
		break;
	default:
		LOG_ERR("Unknown HSC module type(%d)", type);
		return;
	}
	LOG_INF("sen_nums = %d", sen_nums);

	for (uint8_t i = 0; i < ARRAY_SIZE(hsc_sensor_config_table); i++) {
		sensor_cfg *p = hsc_sensor_config_table + i;

		for (uint8_t j = 0; j < sen_nums; j++) {
			if (p->num != *(sen_tbl + j))
				continue;

			// use default address to identify the HSC module
			const uint32_t mfr_id = get_pmbus_mfr_id(p->port, p->target_addr);
			LOG_INF("Sensor %x's HSC module MFR_ID: 0x%06x", p->num, mfr_id);

			switch (mfr_id) {
			case 0:
				/* maybe the board is DVT + XDP710 (addr: 0x28) */
				if (get_pmbus_mfr_id(p->port, dvt_xdp_addr)) {
					p->type = sensor_dev_xdp710;
					p->target_addr = dvt_xdp_addr;
					p->init_args = xdp_init_arr;
				}

				break;
			case XDP710_MFR_ID:
				p->type = sensor_dev_xdp710;
				p->target_addr = dvt_xdp_addr;
				p->init_args = xdp_init_arr;

				break;
			default:
				break;
			}
		}
	}
}

void load_hsc_sensor_config()
{
	/* identify hsc module */
	hsc_config(HSC_CONFIG_FB);
	hsc_config(HSC_CONFIG_BPB);
	hsc_config(HSC_CONFIG_PB);
	hsc_config(HSC_CONFIG_BB);

	for (uint8_t i = 0; i < ARRAY_SIZE(hsc_sensor_config_table); i++)
		add_sensor_config(hsc_sensor_config_table[i]);
}

void load_sb_temp_sensor_config()
{
	/* default sensor config is tmp461
	 * 1st and 2nd source have different i2c addr, identify by i2c addr
	*/
#define TMP461_MFR_ID_OFFSET 0xFE
#define NCT214_MFR_ID_OFFSET 0xFE
#define TMP461_MFR_ID 0x55
#define NCT214_MFR_ID 0x41

	uint8_t temp_mfr_id = 0;
	for (uint8_t i = 0; i < ARRAY_SIZE(tmp461_config_table); i++) {
		temp_mfr_id = get_temp_sensor_mfr_id(tmp461_config_table[i].port,
						     tmp461_config_table[i].target_addr,
						     TMP461_MFR_ID_OFFSET);
		if (temp_mfr_id == TMP461_MFR_ID) {
			add_sensor_config(tmp461_config_table[i]);
			LOG_INF("Add tmp461 %d address on sensorboard ok: 0x%x", i,
				tmp461_config_table[i].target_addr);
			continue;
		} else {
			LOG_INF("Can't read MFR_ID from 0x%x TMP461 , try to read NCT214_MFR_ID",
				tmp461_config_table[i].target_addr);
			temp_mfr_id = get_temp_sensor_mfr_id(nct214_config_table[i].port,
							     nct214_config_table[i].target_addr,
							     NCT214_MFR_ID_OFFSET);
		}

		if (temp_mfr_id == NCT214_MFR_ID) {
			add_sensor_config(nct214_config_table[i]);
			LOG_INF("Add nct214 %d address on sensorboard ok: 0x%x", i,
				nct214_config_table[i].target_addr);
		} else {
			LOG_ERR("Can't read MFR_ID from 0x%x NCT214, load temperature sensor on sensor board failed",
				nct214_config_table[i].target_addr);
			// still add sensor config to keep SENSOR_CONFIG_SIZE correct
			add_sensor_config(tmp461_config_table[i]);
		}
	}
}

void load_plat_def_sensor_config()
{
	uint8_t index = 0;

	for (index = 0; index < ARRAY_SIZE(plat_def_sensor_config); index++)
		add_sensor_config(plat_def_sensor_config[index]);
}

void load_sensor_config(void)
{
	memcpy(sensor_config, plat_sensor_config, sizeof(plat_sensor_config));
	sensor_config_count = ARRAY_SIZE(plat_sensor_config);

	load_hsc_sensor_config();
	load_sb_temp_sensor_config();
	load_plat_def_sensor_config();
}

uint16_t get_sensor_reading_to_modbus_val(uint8_t sensor_num, int8_t exp, int8_t scale)
{
	int reading = 0;
	uint8_t status = get_sensor_reading(sensor_config, sensor_config_count, sensor_num,
					    &reading, GET_FROM_CACHE);

	if (status != SENSOR_READ_SUCCESS) {
		LOG_ERR("0x%02x get sensor cache fail", sensor_num);
		return 0;
	}
	sensor_val *sval = (sensor_val *)&reading;
	float val = (sval->integer * 1000 + sval->fraction) / 1000;
	float r = pow_of_10(exp);
	return val / scale / r; // scale
}

/*
	get real float val from sensor cache
	return sensor status
*/
uint8_t get_sensor_reading_to_real_val(uint8_t sensor_num, float *val)
{
	CHECK_NULL_ARG_WITH_RETURN(val, SENSOR_PARAMETER_NOT_VALID);

	int reading = 0;
	uint8_t status = get_sensor_reading(sensor_config, sensor_config_count, sensor_num,
					    &reading, GET_FROM_CACHE);

	if (status != SENSOR_READ_SUCCESS) {
		LOG_ERR("0x%02x get sensor cache fail", sensor_num);
		return status;
	}

	sensor_val *sval = (sensor_val *)&reading;
	*val = (sval->integer * 1000 + sval->fraction) / 1000;

	return status;
}

/* platform def sensor */
static uint8_t plat_sensor_rpu_pwr[] = {
	SENSOR_NUM_BB_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_BPB_HSC_P48V_PIN_PWR_W,
};

static uint8_t plat_sensor_hex_pwr[] = {
	SENSOR_NUM_FB_1_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_2_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_3_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_4_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_5_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_6_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_7_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_8_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_9_HSC_P48V_PIN_PWR_W,  SENSOR_NUM_FB_10_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_11_HSC_P48V_PIN_PWR_W, SENSOR_NUM_FB_12_HSC_P48V_PIN_PWR_W,
	SENSOR_NUM_FB_13_HSC_P48V_PIN_PWR_W, SENSOR_NUM_FB_14_HSC_P48V_PIN_PWR_W,
};

static uint8_t plat_sensor_hex_curr[] = {
	SENSOR_NUM_FB_1_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_2_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_3_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_4_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_5_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_6_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_7_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_8_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_9_HSC_P48V_IOUT_CURR_A,  SENSOR_NUM_FB_10_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_11_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_FB_12_HSC_P48V_IOUT_CURR_A,
	SENSOR_NUM_FB_13_HSC_P48V_IOUT_CURR_A, SENSOR_NUM_FB_14_HSC_P48V_IOUT_CURR_A,
};

/* Sum the values in the sensor cache in the array */
static float calculate_total_val(uint8_t arr[], uint8_t size)
{
	CHECK_NULL_ARG_WITH_RETURN(arr, 0);

	float total = 0;
	for (uint8_t i = 0; i < size; i++) {
		float tmp = 0;
		if (get_sensor_reading_to_real_val(arr[i], &tmp) == SENSOR_READ_SUCCESS)
			total += tmp;
	}

	return total;
}

static uint8_t plat_def_sensor_read(sensor_cfg *cfg, int *reading)
{
	CHECK_NULL_ARG_WITH_RETURN(cfg, SENSOR_UNSPECIFIED_ERROR);
	CHECK_NULL_ARG_WITH_RETURN(reading, SENSOR_UNSPECIFIED_ERROR);

	uint8_t type = cfg->offset;

	float val = 0;
	switch (type) {
	case PLAT_DEF_SENSOR_RPU_PWR:
		val = calculate_total_val(plat_sensor_rpu_pwr, ARRAY_SIZE(plat_sensor_rpu_pwr));
		break;
	case PLAT_DEF_SENSOR_HEX_PWR:
		val = calculate_total_val(plat_sensor_hex_pwr, ARRAY_SIZE(plat_sensor_hex_pwr));
		break;
	case PLAT_DEF_SENSOR_TOTAL_PWR:
		val = calculate_total_val(plat_sensor_rpu_pwr, ARRAY_SIZE(plat_sensor_rpu_pwr));
		val += calculate_total_val(plat_sensor_hex_pwr, ARRAY_SIZE(plat_sensor_hex_pwr));
		break;
	case PLAT_DEF_SENSOR_HEX_CURR:
		val = calculate_total_val(plat_sensor_hex_curr, ARRAY_SIZE(plat_sensor_hex_curr));
		break;
	default:
		LOG_ERR("0x%02x unknow plat sensor type %d", cfg->num, type);
		return SENSOR_PARAMETER_NOT_VALID;
	}

	sensor_val *sval = (sensor_val *)reading;
	sval->integer = (int)val & 0xFFFF;
	sval->fraction = (val - sval->integer) * 1000;
	return SENSOR_READ_SUCCESS;
}

uint8_t plat_def_sensor_init(sensor_cfg *cfg)
{
	CHECK_NULL_ARG_WITH_RETURN(cfg, SENSOR_INIT_UNSPECIFIED_ERROR);

	cfg->read = plat_def_sensor_read;
	return SENSOR_INIT_SUCCESS;
}
