var dir_b29fe305eacf788491dc55339cb9707f =
[
    [ "plat_class.c", "gt-cc_2src_2platform_2plat__class_8c.html", "gt-cc_2src_2platform_2plat__class_8c" ],
    [ "plat_class.h", "gt-cc_2src_2platform_2plat__class_8h.html", "gt-cc_2src_2platform_2plat__class_8h" ],
    [ "plat_def.h", "gt-cc_2src_2platform_2plat__def_8h.html", "gt-cc_2src_2platform_2plat__def_8h" ],
    [ "plat_fru.c", "gt-cc_2src_2platform_2plat__fru_8c.html", "gt-cc_2src_2platform_2plat__fru_8c" ],
    [ "plat_fru.h", "gt-cc_2src_2platform_2plat__fru_8h.html", "gt-cc_2src_2platform_2plat__fru_8h" ],
    [ "plat_gpio.c", "gt-cc_2src_2platform_2plat__gpio_8c.html", "gt-cc_2src_2platform_2plat__gpio_8c" ],
    [ "plat_gpio.h", "gt-cc_2src_2platform_2plat__gpio_8h.html", "gt-cc_2src_2platform_2plat__gpio_8h" ],
    [ "plat_hook.c", "gt-cc_2src_2platform_2plat__hook_8c.html", "gt-cc_2src_2platform_2plat__hook_8c" ],
    [ "plat_hook.h", "gt-cc_2src_2platform_2plat__hook_8h.html", "gt-cc_2src_2platform_2plat__hook_8h" ],
    [ "plat_i2c.c", "gt-cc_2src_2platform_2plat__i2c_8c.html", null ],
    [ "plat_i2c.h", "gt-cc_2src_2platform_2plat__i2c_8h.html", "gt-cc_2src_2platform_2plat__i2c_8h" ],
    [ "plat_i2c_target.c", "gt-cc_2src_2platform_2plat__i2c__target_8c.html", "gt-cc_2src_2platform_2plat__i2c__target_8c" ],
    [ "plat_i2c_target.h", "gt-cc_2src_2platform_2plat__i2c__target_8h.html", "gt-cc_2src_2platform_2plat__i2c__target_8h" ],
    [ "plat_init.c", "gt-cc_2src_2platform_2plat__init_8c.html", "gt-cc_2src_2platform_2plat__init_8c" ],
    [ "plat_ipmb.c", "gt-cc_2src_2platform_2plat__ipmb_8c.html", "gt-cc_2src_2platform_2plat__ipmb_8c" ],
    [ "plat_ipmb.h", "gt-cc_2src_2platform_2plat__ipmb_8h.html", "gt-cc_2src_2platform_2plat__ipmb_8h" ],
    [ "plat_isr.c", "gt-cc_2src_2platform_2plat__isr_8c.html", "gt-cc_2src_2platform_2plat__isr_8c" ],
    [ "plat_isr.h", "gt-cc_2src_2platform_2plat__isr_8h.html", "gt-cc_2src_2platform_2plat__isr_8h" ],
    [ "plat_led.c", "gt-cc_2src_2platform_2plat__led_8c.html", "gt-cc_2src_2platform_2plat__led_8c" ],
    [ "plat_led.h", "gt-cc_2src_2platform_2plat__led_8h.html", "gt-cc_2src_2platform_2plat__led_8h" ],
    [ "plat_mctp.c", "gt-cc_2src_2platform_2plat__mctp_8c.html", "gt-cc_2src_2platform_2plat__mctp_8c" ],
    [ "plat_mctp.h", "gt-cc_2src_2platform_2plat__mctp_8h.html", "gt-cc_2src_2platform_2plat__mctp_8h" ],
    [ "plat_ncsi.c", "plat__ncsi_8c.html", "plat__ncsi_8c" ],
    [ "plat_ncsi.h", "plat__ncsi_8h.html", "plat__ncsi_8h" ],
    [ "plat_pldm_fw_update.c", "gt-cc_2src_2platform_2plat__pldm__fw__update_8c.html", "gt-cc_2src_2platform_2plat__pldm__fw__update_8c" ],
    [ "plat_pldm_fw_update.h", "gt-cc_2src_2platform_2plat__pldm__fw__update_8h.html", "gt-cc_2src_2platform_2plat__pldm__fw__update_8h" ],
    [ "plat_pldm_monitor.c", "gt-cc_2src_2platform_2plat__pldm__monitor_8c.html", "gt-cc_2src_2platform_2plat__pldm__monitor_8c" ],
    [ "plat_pldm_monitor.h", "gt-cc_2src_2platform_2plat__pldm__monitor_8h.html", "gt-cc_2src_2platform_2plat__pldm__monitor_8h" ],
    [ "plat_sdr_table.c", "gt-cc_2src_2platform_2plat__sdr__table_8c.html", "gt-cc_2src_2platform_2plat__sdr__table_8c" ],
    [ "plat_sdr_table.h", "gt-cc_2src_2platform_2plat__sdr__table_8h.html", "gt-cc_2src_2platform_2plat__sdr__table_8h" ],
    [ "plat_sensor_table.c", "gt-cc_2src_2platform_2plat__sensor__table_8c.html", "gt-cc_2src_2platform_2plat__sensor__table_8c" ],
    [ "plat_sensor_table.h", "gt-cc_2src_2platform_2plat__sensor__table_8h.html", "gt-cc_2src_2platform_2plat__sensor__table_8h" ],
    [ "plat_version.h", "gt-cc_2src_2platform_2plat__version_8h.html", "gt-cc_2src_2platform_2plat__version_8h" ]
];