var dir_062ebb61267edd00864e8af8de6013e4 =
[
    [ "plat_class.c", "gc2-es_2src_2platform_2plat__class_8c.html", "gc2-es_2src_2platform_2plat__class_8c" ],
    [ "plat_class.h", "gc2-es_2src_2platform_2plat__class_8h.html", "gc2-es_2src_2platform_2plat__class_8h" ],
    [ "plat_def.h", "gc2-es_2src_2platform_2plat__def_8h.html", "gc2-es_2src_2platform_2plat__def_8h" ],
    [ "plat_fru.c", "gc2-es_2src_2platform_2plat__fru_8c.html", "gc2-es_2src_2platform_2plat__fru_8c" ],
    [ "plat_fru.h", "gc2-es_2src_2platform_2plat__fru_8h.html", "gc2-es_2src_2platform_2plat__fru_8h" ],
    [ "plat_gpio.c", "gc2-es_2src_2platform_2plat__gpio_8c.html", "gc2-es_2src_2platform_2plat__gpio_8c" ],
    [ "plat_gpio.h", "gc2-es_2src_2platform_2plat__gpio_8h.html", "gc2-es_2src_2platform_2plat__gpio_8h" ],
    [ "plat_guid.c", "gc2-es_2src_2platform_2plat__guid_8c.html", "gc2-es_2src_2platform_2plat__guid_8c" ],
    [ "plat_guid.h", "gc2-es_2src_2platform_2plat__guid_8h.html", null ],
    [ "plat_hook.c", "gc2-es_2src_2platform_2plat__hook_8c.html", "gc2-es_2src_2platform_2plat__hook_8c" ],
    [ "plat_hook.h", "gc2-es_2src_2platform_2plat__hook_8h.html", "gc2-es_2src_2platform_2plat__hook_8h" ],
    [ "plat_i2c.c", "gc2-es_2src_2platform_2plat__i2c_8c.html", null ],
    [ "plat_i2c.h", "gc2-es_2src_2platform_2plat__i2c_8h.html", "gc2-es_2src_2platform_2plat__i2c_8h" ],
    [ "plat_i3c.h", "gc2-es_2src_2platform_2plat__i3c_8h.html", "gc2-es_2src_2platform_2plat__i3c_8h" ],
    [ "plat_init.c", "gc2-es_2src_2platform_2plat__init_8c.html", "gc2-es_2src_2platform_2plat__init_8c" ],
    [ "plat_ipmb.c", "gc2-es_2src_2platform_2plat__ipmb_8c.html", "gc2-es_2src_2platform_2plat__ipmb_8c" ],
    [ "plat_ipmb.h", "gc2-es_2src_2platform_2plat__ipmb_8h.html", "gc2-es_2src_2platform_2plat__ipmb_8h" ],
    [ "plat_isr.c", "gc2-es_2src_2platform_2plat__isr_8c.html", "gc2-es_2src_2platform_2plat__isr_8c" ],
    [ "plat_isr.h", "gc2-es_2src_2platform_2plat__isr_8h.html", "gc2-es_2src_2platform_2plat__isr_8h" ],
    [ "plat_kcs.c", "gc2-es_2src_2platform_2plat__kcs_8c.html", "gc2-es_2src_2platform_2plat__kcs_8c" ],
    [ "plat_kcs.h", "gc2-es_2src_2platform_2plat__kcs_8h.html", "gc2-es_2src_2platform_2plat__kcs_8h" ],
    [ "plat_pmic.c", "gc2-es_2src_2platform_2plat__pmic_8c.html", "gc2-es_2src_2platform_2plat__pmic_8c" ],
    [ "plat_pmic.h", "gc2-es_2src_2platform_2plat__pmic_8h.html", "gc2-es_2src_2platform_2plat__pmic_8h" ],
    [ "plat_sdr_table.c", "gc2-es_2src_2platform_2plat__sdr__table_8c.html", "gc2-es_2src_2platform_2plat__sdr__table_8c" ],
    [ "plat_sdr_table.h", "gc2-es_2src_2platform_2plat__sdr__table_8h.html", "gc2-es_2src_2platform_2plat__sdr__table_8h" ],
    [ "plat_sensor_table.c", "gc2-es_2src_2platform_2plat__sensor__table_8c.html", "gc2-es_2src_2platform_2plat__sensor__table_8c" ],
    [ "plat_sensor_table.h", "gc2-es_2src_2platform_2plat__sensor__table_8h.html", "gc2-es_2src_2platform_2plat__sensor__table_8h" ],
    [ "plat_version.h", "gc2-es_2src_2platform_2plat__version_8h.html", "gc2-es_2src_2platform_2plat__version_8h" ]
];