var dir_4575293aeb41dd94f91988f1aa73171b =
[
    [ "plat_class.c", "yv4-ff_2src_2platform_2plat__class_8c.html", "yv4-ff_2src_2platform_2plat__class_8c" ],
    [ "plat_class.h", "yv4-ff_2src_2platform_2plat__class_8h.html", "yv4-ff_2src_2platform_2plat__class_8h" ],
    [ "plat_def.h", "yv4-ff_2src_2platform_2plat__def_8h.html", "yv4-ff_2src_2platform_2plat__def_8h" ],
    [ "plat_fru.c", "yv4-ff_2src_2platform_2plat__fru_8c.html", "yv4-ff_2src_2platform_2plat__fru_8c" ],
    [ "plat_fru.h", "yv4-ff_2src_2platform_2plat__fru_8h.html", "yv4-ff_2src_2platform_2plat__fru_8h" ],
    [ "plat_gpio.c", "yv4-ff_2src_2platform_2plat__gpio_8c.html", "yv4-ff_2src_2platform_2plat__gpio_8c" ],
    [ "plat_gpio.h", "yv4-ff_2src_2platform_2plat__gpio_8h.html", "yv4-ff_2src_2platform_2plat__gpio_8h" ],
    [ "plat_hook.c", "yv4-ff_2src_2platform_2plat__hook_8c.html", "yv4-ff_2src_2platform_2plat__hook_8c" ],
    [ "plat_hook.h", "yv4-ff_2src_2platform_2plat__hook_8h.html", "yv4-ff_2src_2platform_2plat__hook_8h" ],
    [ "plat_i2c.h", "yv4-ff_2src_2platform_2plat__i2c_8h.html", "yv4-ff_2src_2platform_2plat__i2c_8h" ],
    [ "plat_i2c_target.c", "yv4-ff_2src_2platform_2plat__i2c__target_8c.html", "yv4-ff_2src_2platform_2plat__i2c__target_8c" ],
    [ "plat_i2c_target.h", "yv4-ff_2src_2platform_2plat__i2c__target_8h.html", "yv4-ff_2src_2platform_2plat__i2c__target_8h" ],
    [ "plat_init.c", "yv4-ff_2src_2platform_2plat__init_8c.html", "yv4-ff_2src_2platform_2plat__init_8c" ],
    [ "plat_ipmb.h", "yv4-ff_2src_2platform_2plat__ipmb_8h.html", "yv4-ff_2src_2platform_2plat__ipmb_8h" ],
    [ "plat_isr.c", "yv4-ff_2src_2platform_2plat__isr_8c.html", "yv4-ff_2src_2platform_2plat__isr_8c" ],
    [ "plat_isr.h", "yv4-ff_2src_2platform_2plat__isr_8h.html", "yv4-ff_2src_2platform_2plat__isr_8h" ],
    [ "plat_mctp.c", "yv4-ff_2src_2platform_2plat__mctp_8c.html", "yv4-ff_2src_2platform_2plat__mctp_8c" ],
    [ "plat_mctp.h", "yv4-ff_2src_2platform_2plat__mctp_8h.html", "yv4-ff_2src_2platform_2plat__mctp_8h" ],
    [ "plat_pldm.c", "yv4-ff_2src_2platform_2plat__pldm_8c.html", "yv4-ff_2src_2platform_2plat__pldm_8c" ],
    [ "plat_pldm_fw_update.c", "yv4-ff_2src_2platform_2plat__pldm__fw__update_8c.html", "yv4-ff_2src_2platform_2plat__pldm__fw__update_8c" ],
    [ "plat_pldm_fw_update.h", "yv4-ff_2src_2platform_2plat__pldm__fw__update_8h.html", "yv4-ff_2src_2platform_2plat__pldm__fw__update_8h" ],
    [ "plat_pldm_monitor.c", "yv4-ff_2src_2platform_2plat__pldm__monitor_8c.html", "yv4-ff_2src_2platform_2plat__pldm__monitor_8c" ],
    [ "plat_pldm_monitor.h", "yv4-ff_2src_2platform_2plat__pldm__monitor_8h.html", "yv4-ff_2src_2platform_2plat__pldm__monitor_8h" ],
    [ "plat_pldm_sensor.c", "yv4-ff_2src_2platform_2plat__pldm__sensor_8c.html", "yv4-ff_2src_2platform_2plat__pldm__sensor_8c" ],
    [ "plat_pldm_sensor.h", "yv4-ff_2src_2platform_2plat__pldm__sensor_8h.html", "yv4-ff_2src_2platform_2plat__pldm__sensor_8h" ],
    [ "plat_power_seq.c", "yv4-ff_2src_2platform_2plat__power__seq_8c.html", "yv4-ff_2src_2platform_2plat__power__seq_8c" ],
    [ "plat_power_seq.h", "yv4-ff_2src_2platform_2plat__power__seq_8h.html", "yv4-ff_2src_2platform_2plat__power__seq_8h" ],
    [ "plat_sdr_table.c", "yv4-ff_2src_2platform_2plat__sdr__table_8c.html", "yv4-ff_2src_2platform_2plat__sdr__table_8c" ],
    [ "plat_sdr_table.h", "yv4-ff_2src_2platform_2plat__sdr__table_8h.html", null ],
    [ "plat_sensor_table.c", "yv4-ff_2src_2platform_2plat__sensor__table_8c.html", "yv4-ff_2src_2platform_2plat__sensor__table_8c" ],
    [ "plat_sensor_table.h", "yv4-ff_2src_2platform_2plat__sensor__table_8h.html", null ],
    [ "plat_version.h", "yv4-ff_2src_2platform_2plat__version_8h.html", "yv4-ff_2src_2platform_2plat__version_8h" ]
];