var dir_ae33a0d20050b418b410b34ad4b63e59 =
[
    [ "clock_shell.c", "clock__shell_8c.html", "clock__shell_8c" ],
    [ "clock_shell.h", "clock__shell_8h.html", "clock__shell_8h" ],
    [ "cpld_shell.c", "cpld__shell_8c.html", "cpld__shell_8c" ],
    [ "cpld_shell.h", "cpld__shell_8h.html", "cpld__shell_8h" ],
    [ "fru_shell.c", "fru__shell_8c.html", "fru__shell_8c" ],
    [ "log_shell.c", "log__shell_8c.html", "log__shell_8c" ],
    [ "log_shell.h", "log__shell_8h.html", "log__shell_8h" ],
    [ "plat_aegis_power_control_shell.c", "plat__aegis__power__control__shell_8c.html", "plat__aegis__power__control__shell_8c" ],
    [ "plat_aegis_power_control_shell.h", "plat__aegis__power__control__shell_8h.html", "plat__aegis__power__control__shell_8h" ],
    [ "plat_bootstrap_shell.c", "plat__bootstrap__shell_8c.html", "plat__bootstrap__shell_8c" ],
    [ "plat_echo.c", "plat__echo_8c.html", "plat__echo_8c" ],
    [ "plat_perm_config_shell.c", "plat__perm__config__shell_8c.html", "plat__perm__config__shell_8c" ],
    [ "plat_pldm_fw_version_shell.c", "plat__pldm__fw__version__shell_8c.html", "plat__pldm__fw__version__shell_8c" ],
    [ "plat_pldm_fw_version_shell.h", "plat__pldm__fw__version__shell_8h.html", "plat__pldm__fw__version__shell_8h" ],
    [ "plat_pwrlevel_shell.c", "plat__pwrlevel__shell_8c.html", "plat__pwrlevel__shell_8c" ],
    [ "plat_pwrlevel_shell.h", "plat__pwrlevel__shell_8h.html", "plat__pwrlevel__shell_8h" ],
    [ "plat_sensor_polling_shell.c", "plat__sensor__polling__shell_8c.html", "plat__sensor__polling__shell_8c" ],
    [ "plat_sensor_polling_shell.h", "plat__sensor__polling__shell_8h.html", "plat__sensor__polling__shell_8h" ],
    [ "plat_shell.c", "minerva-ag_2src_2shell_2plat__shell_8c.html", "minerva-ag_2src_2shell_2plat__shell_8c" ],
    [ "plat_smbus_shell.c", "plat__smbus__shell_8c.html", "plat__smbus__shell_8c" ],
    [ "plat_soc_pcie_perst_shell.c", "plat__soc__pcie__perst__shell_8c.html", "plat__soc__pcie__perst__shell_8c" ],
    [ "plat_soc_pwron_reset_shell.c", "plat__soc__pwron__reset__shell_8c.html", "plat__soc__pwron__reset__shell_8c" ],
    [ "plat_temp_status_shell.c", "plat__temp__status__shell_8c.html", "plat__temp__status__shell_8c" ],
    [ "plat_temp_threshold_shell.c", "plat__temp__threshold__shell_8c.html", "plat__temp__threshold__shell_8c" ],
    [ "plat_uart_pwrevent_shell.c", "plat__uart__pwrevent__shell_8c.html", "plat__uart__pwrevent__shell_8c" ],
    [ "plat_uart_pwrevent_shell.h", "plat__uart__pwrevent__shell_8h.html", "plat__uart__pwrevent__shell_8h" ],
    [ "plat_voltage_peak_shell.c", "plat__voltage__peak__shell_8c.html", "plat__voltage__peak__shell_8c" ],
    [ "plat_voltage_peak_shell.h", "plat__voltage__peak__shell_8h.html", "plat__voltage__peak__shell_8h" ],
    [ "plat_voltage_range_shell.c", "plat__voltage__range__shell_8c.html", "plat__voltage__range__shell_8c" ],
    [ "plat_voltage_shell.c", "plat__voltage__shell_8c.html", "plat__voltage__shell_8c" ],
    [ "plat_vr_status_shell.c", "plat__vr__status__shell_8c.html", "plat__vr__status__shell_8c" ],
    [ "sensor_threshold_shell.c", "sensor__threshold__shell_8c.html", "sensor__threshold__shell_8c" ],
    [ "sensor_threshold_shell.h", "sensor__threshold__shell_8h.html", "sensor__threshold__shell_8h" ]
];