manifest:
  remotes:
    - name: aspeed
      url-base: https://github.com/AspeedTech-BMC
    - name: nuvoton
      url-base: https://github.com/Nuvoton-Israel

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: zephyr
      remote: aspeed
      path: zephyr
      revision: 632d2fb5d0438040e8dc44da48a2fb0712c1feea
      import: 
        name-allowlist:
          - cmsis
          - mcuboot
          - mbedtls

    - name: zephyr_nuvoton
      remote: nuvoton
      repo-path: zephyr
      path: zephyr_nuvoton
      revision: openbic-v2.6.0.0

  self:
    path: openbic

