manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  # Please add items below based on alphabetical order.
  # These dependencies may need updating if new features are added to the firmware.
  projects:
    - name: zephyr
      remote: zephyr
      revision: v4.4.0
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nxp

  self:
    path: openbic
