#ifndef PLAT_IPMI_H
#define PLAT_IPMI_H

#include <stdbool.h>
#include <stdint.h>

#define IS_SECTOR_END_MASK 0x80
#define WITHOUT_SENCTOR_END_MASK 0x7F
#define BIC_UPDATE_MAX_OFFSET 0x50000

enum GT_FIRMWARE_COMPONENT {
	GT_COMPNT_VR0,
	GT_COMPNT_VR1,
	GT_COMPNT_BIC,
	GT_COMPNT_PEX0,
	GT_COMPNT_PEX1,
	GT_COMPNT_PEX2,
	GT_COMPNT_PEX3,
	GT_COMPNT_CPLD,
	GT_COMPNT_NIC0,
	GT_COMPNT_NIC1,
	GT_COMPNT_NIC2,
	GT_COMPNT_NIC3,
	GT_COMPNT_NIC4,
	GT_COMPNT_NIC5,
	GT_COMPNT_NIC6,
	GT_COMPNT_NIC7,
	GT_COMPNT_MAX,
};

#endif
