#ifndef PLAT_IPMI_H
#define PLAT_IPMI_H

#include <stdbool.h>
#include <stdint.h>

enum REQ_GET_CARD_TYPE {
	GET_1OU_CARD_TYPE = 0x0,
	GET_2OU_CARD_TYPE,
};

enum DL_FIRMWARE_COMPONENT {
	DL_COMPNT_BIOS = 0,
	DL_COMPNT_CPLD,
	DL_COMPNT_BIC,
	DL_COMPNT_ME,
	DL_COMPNT_BOOTLOADER, // Align to Yv3 TI BIC
	DL_COMPNT_PVCCIN,
	DL_COMPNT_PVCCSA,
	DL_COMPNT_PVCCIO,
	DL_COMPNT_P3V3_STBY,
	DL_COMPNT_PVDDR_ABC,
	DL_COMPNT_PVDDR_DEF
};

#endif
