#ifndef _INTEL_PECI_H
#define _INTEL_PECI_H

enum {
	PECI_UNKNOWN = 0x00,
	PECI_TEMP_CPU_MARGIN,
	PECI_TEMP_CPU,
	PECI_TEMP_CPU_TJMAX,
	PECI_TEMP_CHANNEL0_DIMM0,
	PECI_TEMP_CHANNEL0_DIMM1,
	PECI_TEMP_CHANNEL1_DIMM0,
	PECI_TEMP_CHANNEL1_DIMM1,
	PECI_TEMP_CHANNEL2_DIMM0,
	PECI_TEMP_CHANNEL2_DIMM1,
	PECI_TEMP_CHANNEL3_DIMM0,
	PECI_TEMP_CHANNEL3_DIMM1,
	PECI_TEMP_CHANNEL4_DIMM0,
	PECI_TEMP_CHANNEL4_DIMM1,
	PECI_TEMP_CHANNEL5_DIMM0,
	PECI_TEMP_CHANNEL5_DIMM1,
	PECI_TEMP_CHANNEL6_DIMM0,
	PECI_TEMP_CHANNEL6_DIMM1,
	PECI_TEMP_CHANNEL7_DIMM0,
	PECI_TEMP_CHANNEL7_DIMM1,
	PECI_PWR_CPU,
	PECI_MAX
};

#endif
