#ifndef _INTEL_PECI_H
#define _INTEL_PECI_H

enum {
	PECI_UNKNOWN = 0x00,
	PECI_TEMP_CPU_MARGIN,
	PECI_TEMP_CPU,
	PECI_TEMP_CPU_TJMAX,
	PECI_TEMP_DIMM_A,
	PECI_TEMP_DIMM_C,
	PECI_TEMP_DIMM_D,
	PECI_TEMP_DIMM_E,
	PECI_TEMP_DIMM_G,
	PECI_TEMP_DIMM_H,
	PECI_PWR_CPU,
	PECI_MAX
};

#endif
