#ifndef PLAT_FUNC_H
#define PLAT_FUNC_H

void ISR_POST_COMPLETE();
void ISR_DC_ON();
void ISR_SLP3();
void ISR_DBP_PRSNT();
void ISR_HSC_THROTTLE();
void ISR_MB_THROTTLE();
void ISR_SOC_THMALTRIP();
void ISR_SYS_THROTTLE();
void ISR_HSC_OC();
void ISR_PVDDCR_CPU1_OCP();
void ISR_PVDDCR_CPU0_OCP();
void ISR_PVDD11_S3_OCP();
void ISR_PVDDCR_CPU1_PMALERT();
void ISR_PVDDCR_CPU0_PMALERT();
void ISR_PVDD11_S3_PMALERT();

#endif
