/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "plat_sensor_table.h"

#include <stdio.h>
#include <string.h>

#include "plat_i2c.h"
#include "sensor.h"
#include "ast_adc.h"
#include "plat_hook.h"
#include "plat_class.h"
#include "tmp461.h"
#include "hdc1080.h"
#include "nct7363.h"
#include <logging/log.h>

LOG_MODULE_REGISTER(plat_sensor_table);

#define CONFIG_ISL69260 false

sensor_cfg plat_sensor_config[] = {
	/* number,                  type,       port,      address,      offset,
	   access check arg0, arg1, sample_count, cache, cache_status, mux_address, mux_offset,
	   pre_sensor_read_fn, pre_sensor_read_args, post_sensor_read_fn, post_sensor_read_fn  */

	/* temperature */
	{ SENSOR_NUM_TEMP_BB_TMP75, sensor_dev_tmp75, I2C_BUS4, BB_TMP75_ADDR, TMP75_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_BPB_TMP75, sensor_dev_tmp75, I2C_BUS4, BPB_TMP75_ADDR, TMP75_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_BPB_ADS_1, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_1_ADDR, ADS112C_TEMP_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_BPB_ADS_2, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_2_ADDR, ADS112C_TEMP_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },	
	{ SENSOR_NUM_TEMP_BPB_ADS_3, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_3_ADDR, ADS112C_TEMP_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_MB, sensor_dev_hdc1080, I2C_BUS10, HDC1080_ADDR, HDC1080_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_PDB, sensor_dev_hdc1080, I2C_BUS9, HDC1080_ADDR, HDC1080_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_PB, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR, HDC1080_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },	  
	{ SENSOR_NUM_TEMP_FB_BUS1, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR, HDC1080_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_FB_BUS2, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR, HDC1080_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_FB_BUS6, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR, HDC1080_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_FB_BUS7, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR, HDC1080_TEMP_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_SB_1, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_1_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_TEMP_SB_2, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_2_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },	
	{ SENSOR_NUM_TEMP_SB_3, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_3_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },		  	  	    
	{ SENSOR_NUM_TEMP_SB_4, sensor_dev_tmp461, I2C_BUS9, SB_TMP461_4_ADDR,
	  TMP461_REMOTE_TEMPERATRUE, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },	

	/* pressure */ 
	{ SENSOR_NUM_PRESS_BPB_ADS_1, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR, ADS112C_PRESS_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_PRESS_BPB_ADS_2, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR, ADS112C_PRESS_OFFSET,
	  stby_access, 0, ADS112C_MUX_2_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_PRESS_BPB_ADS_3, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR, ADS112C_PRESS_OFFSET,
	  stby_access, 0, ADS112C_MUX_3_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_PRESS_BPB_ADS_4, sensor_dev_ads112c, I2C_BUS3, BPB_ADS112C_4_ADDR, ADS112C_PRESS_OFFSET,
	  stby_access, 0, ADS112C_MUX_4_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },	

	/* flow */
	{ SENSOR_NUM_FLOW_BPB_ADS, sensor_dev_ads112c, I2C_BUS5, BPB_ADS112C_4_ADDR, ADS112C_FLOW_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },	

	/* leakage */
	{ SENSOR_NUM_LEAK_BPB_ADS_1, sensor_dev_ads112c, I2C_BUS5, BPB_ADS112C_1_ADDR, ADS112C_LEAKAGE_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_LEAK_BPB_ADS_2, sensor_dev_ads112c, I2C_BUS5, BPB_ADS112C_3_ADDR, ADS112C_LEAKAGE_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_LEAK_BPB_ADS_3, sensor_dev_ads112c, I2C_BUS5, BPB_ADS112C_3_ADDR, ADS112C_LEAKAGE_OFFSET,
	  stby_access, 0, ADS112C_MUX_1_CON, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },

	/* fan */
	{ SENSOR_NUM_FAN_BPB_1, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_1_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_BPB_2, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_2_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_BPB_3, sensor_dev_nct7363, I2C_BUS5, BPB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_3_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_FB_BUS1, sensor_dev_nct7363, I2C_BUS1, FB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_1_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_FB_BUS2, sensor_dev_nct7363, I2C_BUS2, FB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_1_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_FB_BUS6, sensor_dev_nct7363, I2C_BUS6, FB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_1_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_FB_BUS7, sensor_dev_nct7363, I2C_BUS7, FB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_1_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_PB_1, sensor_dev_nct7363, I2C_BUS8, BPB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_1_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_PB_2, sensor_dev_nct7363, I2C_BUS8, BPB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_2_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_FAN_PB_3, sensor_dev_nct7363, I2C_BUS8, BPB_NCT7363_ADDR, NCT7363_FAN_SPEED_OFFSET,
	  stby_access, NCT7363_3_FAN, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },	  	  	  	  	  

	/*humility*/
	{ SENSOR_NUM_HUM_MB, sensor_dev_hdc1080, I2C_BUS10, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HUM_PDB, sensor_dev_hdc1080, I2C_BUS9, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HUM_PB, sensor_dev_hdc1080, I2C_BUS8, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,	  
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HUM_FB_BUS1, sensor_dev_hdc1080, I2C_BUS1, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HUM_FB_BUS2, sensor_dev_hdc1080, I2C_BUS2, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HUM_FB_BUS6, sensor_dev_hdc1080, I2C_BUS6, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },
	{ SENSOR_NUM_HUM_FB_BUS7, sensor_dev_hdc1080, I2C_BUS7, HDC1080_ADDR, HDC1080_HUM_OFFSET,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, NULL },	  	  	  	  			  	  
	  	   
};

sensor_cfg adm1272_sensor_config_table[] = {
	{ SENSOR_NUM_TEMP_BB_HSC, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[0] },
	{ SENSOR_NUM_VOL_BB_P51V_STBY, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR, PMBUS_READ_VIN,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_VOL_BB_P51V_AUX, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR, PMBUS_READ_VOUT,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_CUR_BB_P51V_STBY, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR, PMBUS_READ_IIN,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_CUR_BB_P51V_AUX, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR, PMBUS_READ_IOUT,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_PWR_BB_P51V_STBY, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR, PMBUS_READ_EIN,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[0] },
	{ SENSOR_NUM_PWR_BB_P51V_AUX, sensor_dev_adm1272, I2C_BUS4, BB_ADM1272_ADDR, PMBUS_READ_POUT,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[0] },

	{ SENSOR_NUM_TEMP_BPB_HSC, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR,
	  PMBUS_READ_TEMPERATURE_1, stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT,
	  ENABLE_SENSOR_POLLING, 0, SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL,
	  &adm1272_init_args[1] },
	{ SENSOR_NUM_VOL_BPB_P51V_STBY, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR, PMBUS_READ_VIN,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_VOL_BPB_P51V_AUX, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR, PMBUS_READ_VOUT,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, NULL, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_CUR_BPB_P51V_STBY, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR, PMBUS_READ_IIN,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_CUR_BPB_P51V_AUX, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR, PMBUS_READ_IOUT,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_PWR_BPB_P51V_STBY, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR, PMBUS_READ_EIN,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[1] },
	{ SENSOR_NUM_PWR_BPB_P51V_AUX, sensor_dev_adm1272, I2C_BUS4, BPB_ADM1272_ADDR, PMBUS_READ_POUT,
	  stby_access, 0, 0, SAMPLE_COUNT_DEFAULT, POLL_TIME_DEFAULT, ENABLE_SENSOR_POLLING, 0,
	  SENSOR_INIT_STATUS, NULL, NULL, post_adm1272_read, NULL, &adm1272_init_args[1] },	  
};

const int SENSOR_CONFIG_SIZE = ARRAY_SIZE(plat_sensor_config);

void load_sensor_config(void)
{
	memcpy(sensor_config, plat_sensor_config, sizeof(plat_sensor_config));
	sensor_config_count = ARRAY_SIZE(plat_sensor_config);

	pal_extend_sensor_config();
}

void pal_extend_sensor_config()
{
	uint8_t index = 0;
	uint8_t sensor_count = 0;
	uint8_t hsc_module = get_hsc_module();

	switch (hsc_module) {
	case HSC_MODULE_ADM1272:
		sensor_count = ARRAY_SIZE(adm1272_sensor_config_table);
		for (index = 0; index < sensor_count; index++) {
			add_sensor_config(adm1272_sensor_config_table[index]);
		}
		break;
	default:
		LOG_ERR("Invalid hsc module: 0x%x", hsc_module);
		break;
	}
}
