/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef PLAT_PLDM_SENSOR_H
#define PLAT_PLDM_SENSOR_H

#include "pdr.h"
#include "sensor.h"

#define QUICK_POLL_INTERVAL 1000

#define ADDR_UNKNOWN (0xFF >> 1)

// sensor addr (7-bit)
// page 70
#define TOP_INLET_ADDR (0x92 >> 1)
#define BOT_INLET_ADDR (0x94 >> 1)
#define BOT_OUTLET_ADDR (0x96 >> 1)
// page 49
#define ASIC_NUWA0_SENSOR0_ADDR (0x98 >> 1)
#define ASIC_NUWA0_SENSOR1_ADDR (0x98 >> 1)
#define ASIC_OWL_W_ADDR (0x9A >> 1)
#define ASIC_OWL_E_ADDR (0x9A >> 1)
#define ASIC_HAMSA_CRM_ADDR (0x98 >> 1)
#define ASIC_HAMSA_LS_ADDR (0x98 >> 1)
#define ASIC_NUWA1_SENSOR0_ADDR (0x9A >> 1)
#define ASIC_NUWA1_SENSOR1_ADDR (0x9A >> 1)

// VR_MODULE_MPS module addr
//PU438
#define ASIC_P0V75_NUWA0_VDD_ADDR (0x50 >> 1)
//PU437
#define ASIC_P0V75_NUWA1_VDD_ADDR (0x4C >> 1)
//PU535
#define ASIC_P0V9_OWL_E_TRVDD_ADDR (0xEE >> 1)
#define ASIC_P0V75_OWL_E_TRVDD_ADDR (0xEE >> 1)
//PU522
#define ASIC_P0V75_MAX_M_VDD_ADDR (0xEA >> 1)
#define ASIC_P0V75_VDDPHY_HBM1357_ADDR (0xEA >> 1)
//PU556
#define ASIC_P0V75_OWL_E_VDD_ADDR (0xE2 >> 1)
#define ASIC_P0V4_VDDQL_HBM1357_ADDR (0xE2 >> 1)
//PU521
#define ASIC_P1V05_VDDQC_HBM1357_ADDR (0xEC >> 1)
#define ASIC_P1V8_VPP_HBM1357_ADDR (0xEC >> 1)
//PU634
#define ASIC_P0V9_VDDQ_HBM1357_ADDR (0xD0 >> 1)
#define ASIC_P0V85_HAMSA_VDD_ADDR (0xD0 >> 1)
//PU505
#define ASIC_P0V75_MAX_N_VDD_ADDR (0xF6 >> 1)
#define ASIC_P0V8_HAMSA_AVDD_PCIE_ADDR (0xF6 >> 1)
//PU508
#define ASIC_P0V9_VDDQ_HBM0246_ADDR (0xF2 >> 1)
#define ASIC_P1V2_HAMSA_VDDHRXTX_PCIE_ADDR (0xF2 >> 1)
//PU312
#define ASIC_P1V05_VDDQC_HBM0246_ADDR (0xE0 >> 1)
#define ASIC_P1V8_VPP_HBM0246_ADDR (0xE0 >> 1)
//PU504
#define ASIC_P0V4_VDDQL_HBM0246_ADDR (0xE4 >> 1)
#define ASIC_P0V75_VDDPHY_HBM0246_ADDR (0xE4 >> 1)
//PU551
#define ASIC_P0V75_OWL_W_VDD_ADDR (0xE6 >> 1)
#define ASIC_P0V75_MAX_S_VDD_ADDR (0xE6 >> 1)
//PU624
#define ASIC_P0V9_OWL_W_TRVDD_ADDR (0xF8 >> 1)
#define ASIC_P0V75_OWL_W_TRVDD_ADDR (0xF8 >> 1)

// VR_MODULE_RNS module addr
// PU438
#define ASIC_P0V75_NUWA0_VDD_RNS_ADDR (0xEC >> 1)
// PU437
#define ASIC_P0V75_NUWA1_VDD_RNS_ADDR (0xE4 >> 1)
// PU535
#define ASIC_P0V9_OWL_E_TRVDD_RNS_ADDR (0xC4 >> 1)
#define ASIC_P0V75_OWL_E_TRVDD_RNS_ADDR (0xC4 >> 1)
// PU522
#define ASIC_P0V75_MAX_M_VDD_RNS_ADDR (0xE8 >> 1)
#define ASIC_P0V75_VDDPHY_HBM1357_RNS_ADDR (0xE8 >> 1)
// PU556
#define ASIC_P0V75_OWL_E_VDD_RNS_ADDR (0xC2 >> 1)
#define ASIC_P0V4_VDDQL_HBM1357_RNS_ADDR (0xC2 >> 1)
// PU521
#define ASIC_P1V05_VDDQC_HBM1357_RNS_ADDR (0xC6 >> 1)
#define ASIC_P1V8_VPP_HBM1357_RNS_ADDR (0xC6 >> 1)
// PU634
#define ASIC_P0V9_VDDQ_HBM1357_RNS_ADDR (0xEA >> 1)
#define ASIC_P0V85_HAMSA_VDD_RNS_ADDR (0xEA >> 1)
// PU505
#define ASIC_P0V75_MAX_N_VDD_RNS_ADDR (0xC2 >> 1)
#define ASIC_P0V8_HAMSA_AVDD_PCIE_RNS_ADDR (0xC2 >> 1)
// PU508
#define ASIC_P0V9_VDDQ_HBM0246_RNS_ADDR (0xC6 >> 1)
#define ASIC_P1V2_HAMSA_VDDHRXTX_PCIE_RNS_ADDR (0xC6 >> 1)
// PU312
#define ASIC_P1V05_VDDQC_HBM0246_RNS_ADDR (0xC0 >> 1)
#define ASIC_P1V8_VPP_HBM0246_RNS_ADDR (0xC0 >> 1)
// PU504
#define ASIC_P0V4_VDDQL_HBM0246_RNS_ADDR (0xE8 >> 1)
#define ASIC_P0V75_VDDPHY_HBM0246_RNS_ADDR (0xE8 >> 1)
// PU551
#define ASIC_P0V75_OWL_W_VDD_RNS_ADDR (0xC4 >> 1)
#define ASIC_P0V75_MAX_S_VDD_RNS_ADDR (0xC4 >> 1)
// PU624
#define ASIC_P0V9_OWL_W_TRVDD_RNS_ADDR (0xEA >> 1)
#define ASIC_P0V75_OWL_W_TRVDD_RNS_ADDR (0xEA >> 1)

// page 166
#define UBC1_ADDR (0x2E >> 1)
#define UBC2_ADDR (0x34 >> 1)

#define P3V3_OSFP_ADDR (0xFA >> 1)

// sensor number
enum SENSOR_NUM_LIST {
	// tmp
	SENSOR_NUM_TOP_INLET_TEMP_C = 0x01,
	SENSOR_NUM_BOT_INLET_TEMP_C,
	SENSOR_NUM_BOT_OUTLET_TEMP_C,
	SENSOR_NUM_ASIC_NUWA0_SENSOR0_TEMP_C,
	SENSOR_NUM_ASIC_NUWA0_SENSOR1_TEMP_C,
	SENSOR_NUM_ASIC_OWL_W_TEMP_C,
	SENSOR_NUM_ASIC_OWL_E_TEMP_C,
	SENSOR_NUM_ASIC_NUWA1_SENSOR0_TEMP_C,
	SENSOR_NUM_ASIC_NUWA1_SENSOR1_TEMP_C,
	SENSOR_NUM_ASIC_HAMSA_CRM_TEMP_C,
	SENSOR_NUM_ASIC_HAMSA_LS_TEMP_C,
	// VR
	SENSOR_NUM_ASIC_P0V75_NUWA0_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_NUWA0_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_NUWA0_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_NUWA0_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_NUWA1_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_NUWA1_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_NUWA1_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_NUWA1_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V9_OWL_E_TRVDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V9_OWL_E_TRVDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_OWL_E_TRVDD_CURR_A,
	SENSOR_NUM_ASIC_P0V9_OWL_E_TRVDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_OWL_E_TRVDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_OWL_E_TRVDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_E_TRVDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_OWL_E_TRVDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_OWL_E_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_OWL_E_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_E_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_OWL_E_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V9_OWL_W_TRVDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V9_OWL_W_TRVDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_OWL_W_TRVDD_CURR_A,
	SENSOR_NUM_ASIC_P0V9_OWL_W_TRVDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_OWL_W_TRVDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_OWL_W_TRVDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_W_TRVDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_OWL_W_TRVDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_OWL_W_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_OWL_W_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_W_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_OWL_W_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_MAX_M_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_MAX_M_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_MAX_M_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_MAX_M_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_MAX_N_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_MAX_N_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_MAX_N_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_MAX_N_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_MAX_S_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_MAX_S_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_MAX_S_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V75_MAX_S_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V8_HAMSA_AVDD_PCIE_TEMP_C,
	SENSOR_NUM_ASIC_P0V8_HAMSA_AVDD_PCIE_VOLT_V,
	SENSOR_NUM_ASIC_P0V8_HAMSA_AVDD_PCIE_CURR_A,
	SENSOR_NUM_ASIC_P0V8_HAMSA_AVDD_PCIE_PWR_W,
	SENSOR_NUM_ASIC_P1V2_HAMSA_VDDHRXTX_PCIE_TEMP_C,
	SENSOR_NUM_ASIC_P1V2_HAMSA_VDDHRXTX_PCIE_VOLT_V,
	SENSOR_NUM_ASIC_P1V2_HAMSA_VDDHRXTX_PCIE_CURR_A,
	SENSOR_NUM_ASIC_P1V2_HAMSA_VDDHRXTX_PCIE_PWR_W,
	SENSOR_NUM_ASIC_P0V85_HAMSA_VDD_TEMP_C,
	SENSOR_NUM_ASIC_P0V85_HAMSA_VDD_VOLT_V,
	SENSOR_NUM_ASIC_P0V85_HAMSA_VDD_CURR_A,
	SENSOR_NUM_ASIC_P0V85_HAMSA_VDD_PWR_W,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM0246_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM0246_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM0246_CURR_A,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM0246_PWR_W,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM0246_TEMP_C,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM0246_VOLT_V,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM0246_CURR_A,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM0246_PWR_W,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM0246_TEMP_C,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM0246_VOLT_V,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM0246_CURR_A,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM0246_PWR_W,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM0246_TEMP_C,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM0246_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM0246_CURR_A,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM0246_PWR_W,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM0246_TEMP_C,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM0246_VOLT_V,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM0246_CURR_A,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM0246_PWR_W,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM1357_TEMP_C,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM1357_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM1357_CURR_A,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM1357_PWR_W,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM1357_TEMP_C,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM1357_VOLT_V,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM1357_CURR_A,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM1357_PWR_W,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM1357_TEMP_C,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM1357_VOLT_V,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM1357_CURR_A,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM1357_PWR_W,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM1357_TEMP_C,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM1357_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM1357_CURR_A,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM1357_PWR_W,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM1357_TEMP_C,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM1357_VOLT_V,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM1357_CURR_A,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM1357_PWR_W,
	// UBC
	SENSOR_NUM_UBC1_P12V_TEMP_C,
	SENSOR_NUM_UBC1_P12V_VOLT_V,
	SENSOR_NUM_UBC1_P12V_CURR_A,
	SENSOR_NUM_UBC1_P12V_PWR_W,
	SENSOR_NUM_UBC1_P52V_INPUT_VOLT_V,
	SENSOR_NUM_UBC2_P12V_TEMP_C,
	SENSOR_NUM_UBC2_P12V_VOLT_V,
	SENSOR_NUM_UBC2_P12V_CURR_A,
	SENSOR_NUM_UBC2_P12V_PWR_W,
	SENSOR_NUM_UBC2_P52V_INPUT_VOLT_V,
	// VR Vin
	SENSOR_NUM_ASIC_P0V75_NUWA0_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_NUWA1_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_OWL_E_TRVDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_E_TRVDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_MAX_M_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM1357_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_E_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM1357_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM1357_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM1357_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM1357_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V85_HAMSA_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_MAX_N_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V8_HAMSA_AVDD_PCIE_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_VDDQ_HBM0246_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P1V2_HAMSA_VDDHRXTX_PCIE_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P1V05_VDDQC_HBM0246_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P1V8_VPP_HBM0246_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V4_VDDQL_HBM0246_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_VDDPHY_HBM0246_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_W_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_MAX_S_VDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V9_OWL_W_TRVDD_INPUT_VOLT_V,
	SENSOR_NUM_ASIC_P0V75_OWL_W_TRVDD_INPUT_VOLT_V,
	SENSOR_NUM_NUMBERS,
};

#define TMP75_TEMP_OFFSET 0x00
#define UPDATE_INTERVAL_1S 1
#define UPDATE_INTERVAL_5S 5
#define UPDATE_INTERVAL_60S 60
#define U200051_IO_ADDR (0x72 >> 1)

#define ONE_STEP_POWER_MAGIC_NUMBER 0x56

enum SENSOR_THREAD_LIST {
	TEMP_SENSOR_THREAD_ID = 0,
	VR_SENSOR_THREAD_ID,
	QUICK_VR_SENSOR_THREAD_ID,
	UBC_SENSOR_THREAD_ID,
	MAX_SENSOR_THREAD_ID,
};

enum PCA9554APW_REG { INPUT_PORT = 0, OUTPUT_PORT = 1, POLARITY_INVERSION = 2, CONFIG = 3 };

enum VR_ADDRESS_VIRSION { OLD_MPS = 0, OLD_RNS, MAX_VR_ADDRESS_VIRSION };

int plat_pldm_sensor_get_sensor_count(int thread_id);
sensor_cfg *get_sensor_cfg_by_sensor_id(uint8_t sensor_id);
void plat_pldm_sensor_get_pdr_numeric_sensor(int thread_id, int sensor_num,
					     PDR_numeric_sensor *numeric_sensor_table);
bool is_dc_access(uint8_t sensor_num);
void set_plat_sensor_polling_enable_flag(bool value);
void set_plat_sensor_ubc_polling_enable_flag(bool value);
void set_plat_sensor_temp_polling_enable_flag(bool value);
void set_plat_sensor_vr_polling_enable_flag(bool value);
void set_plat_sensor_one_step_enable_flag(uint8_t value);
bool get_plat_sensor_polling_enable_flag();
bool get_plat_sensor_ubc_polling_enable_flag();
bool get_plat_sensor_temp_polling_enable_flag();
bool get_plat_sensor_vr_polling_enable_flag();
uint8_t get_plat_sensor_one_step_enable_flag();
bool is_ubc_access(uint8_t sensor_num);
bool is_temp_access(uint8_t cfg_idx);
bool is_vr_access(uint8_t sensor_num);
size_t char16_strlen(const char16_t *str);
char16_t *char16_strcpy(char16_t *dest, const char16_t *src);
char16_t *char16_strcat_char(char16_t *dest, char16_t ch);

bool get_raw_data_from_sensor_id(uint8_t sensor_id, uint8_t offset, uint8_t *val, uint8_t len);
void change_sensor_cfg(uint8_t asic_board_id, uint8_t vr_module, uint8_t ubc_module,
		       uint8_t board_rev_id);
uint8_t convert_vr_addr(uint8_t addr, uint8_t vr_change_mode);
uint32_t plat_get_pdr_size(uint8_t pdr_type);
uint32_t plat_pldm_sensor_get_quick_vr_poll_interval();
void plat_pldm_sensor_set_quick_vr_poll_interval(uint32_t value);
void init_U200051_IO();
void quick_sensor_poll_init();
void set_ioe_init_flag(uint8_t flag);
uint8_t get_ioe_init_flag();
PDR_numeric_sensor *get_pdr_numeric_sensor_by_sensor_id(uint8_t sensor_id);
#endif
