diff --git a/portable/MemMang/Makefile b/portable/MemMang/Makefile
new file mode 100644
index 000000000..e87da027c
--- /dev/null
+++ b/portable/MemMang/Makefile
@@ -0,0 +1,8 @@
+-include $(KCONFIG_CONFIG)
+
+obj-$(CONFIG_HEAP_1) += heap_1.o
+obj-$(CONFIG_HEAP_2) += heap_2.o
+obj-$(CONFIG_HEAP_3) += heap_3.o
+obj-$(CONFIG_HEAP_4) += heap_4.o
+obj-$(CONFIG_HEAP_4) += heap_4_nc.o
+obj-$(CONFIG_HEAP_5) += heap_5.o
\ No newline at end of file
